delete from mb_event_part where EVENT_TYPE = 'WTD_RB101' and ASSEMBLE_ID ='CHECK_KEEP_BAL_PA';
INSERT INTO mb_event_part (EVENT_TYPE, ASSEMBLE_ID, ATTR_KEY, ATTR_VALUE) VALUES ('WTD_RB101', 'CHECK_KEEP_BAL_PA', 'ACTUAL_OR_LEDGER_BAL', 'A');
INSERT INTO mb_event_part (EVENT_TYPE, ASSEMBLE_ID, ATTR_KEY, ATTR_VALUE) VALUES ('WTD_RB101', 'CHECK_KEEP_BAL_PA', 'CHECK_KEEP_BAL', 'Y');
INSERT INTO mb_event_part (EVENT_TYPE, ASSEMBLE_ID, ATTR_KEY, ATTR_VALUE) VALUES ('WTD_RB101', 'CHECK_KEEP_BAL_PA', 'KEEP_MAX_BAL', '20000');
INSERT INTO mb_event_part (EVENT_TYPE, ASSEMBLE_ID, ATTR_KEY, ATTR_VALUE) VALUES ('WTD_RB101', 'CHECK_KEEP_BAL_PA', 'KEEP_MIN_BAL', '0');


delete from mb_event_attr where EVENT_TYPE ='WTD_RB101';
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '1', 'PART', 'CHECK_ACCT_STATUS_PA', NULL, 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '10', 'ATTR', 'CHECK_AGENT', 'Y', 'C');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '11', 'ATTR', 'AMT_CALC_TYPE', '1', 'F');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '12', 'PART', 'CHECK_TRAN_LIMIT_PA', NULL, 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '13', 'ATTR', 'AGENT_FLAG', 'Y', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '14', 'ATTR', 'FUND_TRAN_TYPE', 'C', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '15', 'ATTR', 'SG_MAX_AMT', '10000', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '16', 'ATTR', 'SG_MIN_AMT', '100', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '18', 'ATTR', 'WITHDRAWAL_TYPE', 'Y', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '19', 'ATTR', 'CHECK_DOC_TYPE', 'N', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '2', 'ATTR', 'CHECK_RESTRAINT', 'N', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '20', 'ATTR', 'DRAW_BREAK_TYPE', 'D', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '21', 'ATTR', 'BREAK_DEAL_WAY', 'D', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '3', 'PART', 'CHECK_FUND_TRAN_PA', NULL, 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '4', 'PART', 'CHECK_SG_AMT_PA', NULL, 'F');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '5', 'PART', 'CHECK_KEEP_BAL_PA', NULL, 'F');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '6', 'PART', 'DRA_DEP_PA', NULL, 'F');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '8', 'ATTR', 'CHECK_WDRAWN_TYPE', 'Y', 'A');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '9', 'ATTR', 'SERV_CHARGE_FLAG', 'N', 'C');
commit;

DELETE FROM mb_event_part WHERE EVENT_TYPE='WTD_RB101' AND ASSEMBLE_ID='CHECK_SG_AMT_PA';
INSERT INTO mb_event_part (EVENT_TYPE, ASSEMBLE_ID, ATTR_KEY, ATTR_VALUE) VALUES ('WTD_RB101', 'CHECK_SG_AMT_PA', 'CHECK_SG_AMT', 'Y');
INSERT INTO mb_event_part (EVENT_TYPE, ASSEMBLE_ID, ATTR_KEY, ATTR_VALUE) VALUES ('WTD_RB101', 'CHECK_SG_AMT_PA', 'SG_MAX_AMT', '999999999999999');
INSERT INTO mb_event_part (EVENT_TYPE, ASSEMBLE_ID, ATTR_KEY, ATTR_VALUE) VALUES ('WTD_RB101', 'CHECK_SG_AMT_PA', 'SG_MIN_AMT', '50000');
COMMIT;