INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '18', 'ATTR', 'WITHDRAWAL_TYPE', 'Y', 'A');
UPDATE mb_event_attr SET EVENT_TYPE='DEP_RB101', SEQ_NO='6', ASSEMBLE_TYPE='PART', ASSEMBLE_ID='CHECK_KEEP_BAL_PA', ATTR_VALUE='Y', ASSEMBLE_RULE='A' WHERE (EVENT_TYPE='DEP_RB101') AND (SEQ_NO='6');
UPDATE mb_event_attr SET EVENT_TYPE='WTD_RB101', SEQ_NO='5', ASSEMBLE_TYPE='PART', ASSEMBLE_ID='CHECK_KEEP_BAL_PA', ATTR_VALUE='Y', ASSEMBLE_RULE='F' WHERE (EVENT_TYPE='WTD_RB101') AND (SEQ_NO='5');
INSERT INTO mb_event_attr (EVENT_TYPE, SEQ_NO, ASSEMBLE_TYPE, ASSEMBLE_ID, ATTR_VALUE, ASSEMBLE_RULE) VALUES ('WTD_RB101', '19', 'ATTR', 'CHECK_KEEP_BAL', 'Y', 'A');
commit;