INSERT INTO MB_PART_CLASS (PART_CLASS,PART_CLASS_DESC,PART_CLASS_LEVEL,PARENT_PART_CLASS) VALUES ('ACCT', '账户信息', '1', null);
INSERT INTO MB_PART_CLASS (PART_CLASS,PART_CLASS_DESC,PART_CLASS_LEVEL,PARENT_PART_CLASS) VALUES ('AGREEMENT', '协议信息', '1', null);
INSERT INTO MB_PART_CLASS (PART_CLASS,PART_CLASS_DESC,PART_CLASS_LEVEL,PARENT_PART_CLASS) VALUES ('BALANCE', '余额信息', '1', null);
INSERT INTO MB_PART_CLASS (PART_CLASS,PART_CLASS_DESC,PART_CLASS_LEVEL,PARENT_PART_CLASS) VALUES ('CLIENT', '客户信息', '1', null);
INSERT INTO MB_PART_CLASS (PART_CLASS,PART_CLASS_DESC,PART_CLASS_LEVEL,PARENT_PART_CLASS) VALUES ('FREQUCY', '期限信息', '1', null);
INSERT INTO MB_PART_CLASS (PART_CLASS,PART_CLASS_DESC,PART_CLASS_LEVEL,PARENT_PART_CLASS) VALUES ('MEDIA', '介质信息', '1', null);
INSERT INTO MB_PART_CLASS (PART_CLASS,PART_CLASS_DESC,PART_CLASS_LEVEL,PARENT_PART_CLASS) VALUES ('PRICE', '定价信息', '1', null);
INSERT INTO MB_PART_CLASS (PART_CLASS,PART_CLASS_DESC,PART_CLASS_LEVEL,PARENT_PART_CLASS) VALUES ('RISK', '风险信息', '1', null);