TRUNCATE TABLE gl_currency_seqno_def;
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AUD', '5', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CAD', '6', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CHF', '7', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CNY', '1', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('EUR', '8', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('GBP', '9', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('HKD', '10', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('JPY', '11', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('SGD', '12', NULL, NULL);
INSERT INTO gl_currency_seqno_def (CCY, GL_SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('USD', '13', NULL, NULL);

COMMIT;
