TRUNCATE TABLE gl_ccy_adjust_table;
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AUD', 'CNY', '30020304', 'RER', NULL, NULL);
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CAD', 'CNY', '30020304', 'RER', NULL, NULL);
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CHF', 'CNY', '30020304', 'RER', NULL, NULL);
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('EUR', 'CNY', '30020304', 'RER', NULL, NULL);
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('GBP', 'CNY', '30020304', 'RER', NULL, NULL);
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('JPY', 'CNY', '30020304', 'RER', NULL, NULL);
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('HKD', 'CNY', '30020304', 'RER', NULL, NULL);
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('SGD', 'CNY', '30020304', 'RER', NULL, NULL);
INSERT INTO gl_ccy_adjust_table (CCY, ADJUST_CCY, SUBJECT_CODE, RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('USD', 'CNY', '30020304', 'RER', NULL, NULL);

COMMIT;
