TRUNCATE TABLE gl_reserve_type;
INSERT INTO gl_reserve_type (PAY_TYPE, PAY_TYPE_DESC, BASE_RATE_TYPE, PERIOD_PAY_IND, PAY_PERIOD_FREQ, FREQ_DAY, NEXT_PAY_DATE, LAST_PAY_DATE, PAY_RATE, PAY_WAY, AUTO_ACCOUNTING, MIDDLE_TEN_DAY, FIRST_TEN_DAY, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('1', '法定准备金', 'HBD', 'Y', NULL, NULL, '20180630', '20180620', '8', 'AVG', 'N', '20', '10', NULL, NULL);
INSERT INTO gl_reserve_type (PAY_TYPE, PAY_TYPE_DESC, BASE_RATE_TYPE, PERIOD_PAY_IND, PAY_PERIOD_FREQ, FREQ_DAY, NEXT_PAY_DATE, LAST_PAY_DATE, PAY_RATE, PAY_WAY, AUTO_ACCOUNTING, MIDDLE_TEN_DAY, FIRST_TEN_DAY, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('2', '财政性存款', 'HBD', 'Y', NULL, NULL, '20180630', '20180620', '100', 'BAL', 'N', '20', '10', NULL, NULL);
INSERT INTO gl_reserve_type (PAY_TYPE, PAY_TYPE_DESC, BASE_RATE_TYPE, PERIOD_PAY_IND, PAY_PERIOD_FREQ, FREQ_DAY, NEXT_PAY_DATE, LAST_PAY_DATE, PAY_RATE, PAY_WAY, AUTO_ACCOUNTING, MIDDLE_TEN_DAY, FIRST_TEN_DAY, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('3', '外币准备金', 'HBD', 'N', 'ML', NULL, '20180630', '20180531', '3', 'BAL', 'N', NULL, NULL, NULL, NULL);

COMMIT;
