drop table if exists BAT_CIF_BASE_CORP;
/*==============================================================*/
/* Table: BAT_CIF_BASE_CORP                                           */
/*==============================================================*/
create table BAT_CIF_BASE_CORP
(
    PARTY_ID varchar(20) comment '客户号',
    PARTY_CLAS_CODE varchar(10) comment '参与方分类代码',
    PARTY_STATUS_CODE varchar(10) comment '参与方状态',
    PARTY_TYPE_CODE varchar(10) comment '参与方类型代码',
    CTRL_BRANCH varchar(20) comment '归属机构',
    CUST_MGR varchar(10) comment '归属客户经理代码',
    PARTY_ROLE_TYPE_CODE varchar(10) comment '参与方角色代码',
    CUST_NAME2 varchar(200) comment '客户名称（中）',
    PARTY_ID2 varchar(20) comment '客户号',
    PARTY_CLAS_CODE2 varchar(10) comment '参与方分类代码',
    PARTY_STATUS_CODE2 varchar(10) comment '参与方状态',
    PARTY_TYPE_CODE2 varchar(10) comment '参与方类型代码',
    CTRL_BRANCH2 varchar(10) comment '归属机构',
    CUST_MGR2 varchar(10) comment '归属客户经理代码',
    PARTY_ROLE_TYPE_CODE2 varchar(10) comment '参与方角色代码',
    CUST_NAME varchar(200) comment '客户名称（中）',
    EN_CUST_NAME varchar(200) comment '客户名称（英）',
    CUST_TYPE varchar(10) comment '客户类型',
    GENDER_CODE varchar(10) comment '客户细类',
    CENTRAL_BANK_INDUSTRY_CODE varchar(10) comment '人行行业类型',
    INDUSTRY_CODE varchar(10) comment '行业类型_国家标准',
    CAPITAL_CCY varchar(3) comment '注册资本币种',
    CAPITAL_AMT Decimal(17,2) comment '注册资本',
    DEPARTMENT_INDUSTRY_CODE varchar(10) comment '四部委行业分类',
    EMP_NUM varchar(10) comment '员工数',
    ASSET_AMT Decimal(20,2) comment '资产总额',
    SALE_AMT Decimal(20,2) comment '年销售额',
    COMPANY_SIZE varchar(10) comment '企业规模',
    ACCOUNTING_YEAR_MONTH varchar(6) comment '会计年月',
    OTHER_DOC_NAME varchar(200) comment '其他证明文件名称',
    CAPITAL_VERIFICATION_CUST varchar(10) comment '注册验资户',
    CLASS4 varchar(10) comment '分类4',
    ECON_DIST varchar(3) comment '特殊经济区域代码',
    INLAND_OFFSHORE varchar(1) comment '境内境外',
    HIGH_LEVEL_ORG_NAME varchar(200) comment '上级法人或主管单位名称',
    HIGH_LEVEL_ORG_CODE varchar(30) comment '上级法人或主管单位组织机构代码',
    IS_GROUP_FLAG varchar(10) comment '集团客户标志',
    GROUP_MEMBER_TYPE varchar(10) comment '集团成员公司类型',
    RELATION_TYPE varchar(10) comment '与我行关系',
    CUST_LEVEL varchar(10) comment '客户等级',
    RISK_CONTROL_BRANCH varchar(10) comment '反洗钱主管行',
    MONEY_LAUNDERING_RISK_GRADE varchar(10) comment '洗钱客户风险评级',
    MONEY_LAUNDERING_RISK_REASON varchar(10) comment '洗钱风险评级理由',
    FRIST_JUDGE_DATE varchar(8) comment '首次评级日期',
    CHG_JUDGE_DATE varchar(8) comment '变更评级日期',
    REMARK varchar(200) comment '备注',
    INTERNAL_IND varchar(1) comment '内部客户',
    CREDIT_LEVEL varchar(10) comment '信用等级',
    CLIENT_INDICATOR varchar(1) comment '客户标识',
    IS_BLACK_LIST varchar(10) comment '是否黑名单',
    SRC_UPDATED_TS timestamp comment '源系统更新时间',
    UPDATED_SYSTEM_ID varchar(10) comment '更新外部系统号',
    INVALID_DATE varchar(8) comment '失效日期'
);
alter table BAT_CIF_BASE_CORP comment '对公客户基本信息 undefined';