drop table if exists BAT_CIF_INDVL;
/*==============================================================*/
/* Table: BAT_CIF_INDVL                                           */
/*==============================================================*/
create table BAT_CIF_INDVL
(
    PARTY_ID varchar(20) comment '客户号',
    PARTY_CLAS_CODE varchar(10) comment '参与方分类代码',
    PARTY_STATUS_CODE varchar(10) comment '参与方状态',
    PARTY_TYPE_CODE varchar(10) comment '参与方类型代码',
    CTRL_BRANCH varchar(20) comment '控制分行 ',
    CUST_MGR varchar(10) comment '归属客户经理代码',
    PARTY_ROLE_TYPE_CODE varchar(10) comment '参与方角色代码',
    CUST_NAME varchar(200) comment '客户名称（中）',
    EN_CUST_NAME varchar(200) comment '客户名称（英）',
    BIRTH_DATE varchar(8) comment '出生日期',
    GENDER_CODE varchar(10) comment '性别',
    RACE varchar(10) comment '民族代码',
    IS_EMPLOYEE_FLAG varchar(10) comment '员工标志',
    IS_AGENT varchar(10) comment '是否代理',
    MONEY_LAUNDERING_RISK_GRADE varchar(10) comment '洗钱客户风险评级',
    MONEY_LAUNDERING_RISK_REASON varchar(10) comment '洗钱风险评级理由',
    RISK_CONTROL_BRANCH varchar(10) comment '反洗钱主管行',
    RESIDENCE_TYPE varchar(10) comment '居民类型',
    IN_OUT_FLAG varchar(10) comment '境内境外',
    RISK_SUPPORT_ABILITY varchar(10) comment '客户风险承受能力',
    CUST_TYPE varchar(10) comment '客户类型',
    CUST_LEVEL varchar(10) comment '客户等级',
    CREDIT_LEVEL varchar(10) comment '信用等级',
    HOLD_CARD_LEVEL varchar(10) comment '持卡等级',
    IS_BLACK_LIST varchar(10) comment '是否黑名单',
    OTHER_CLASS varchar(10) comment '其他分类',
    MARITAL_STATUS varchar(1) comment '婚姻状况',
    EDUCATION_CODE varchar(10) comment '最高学历',
    EDUCATION_ACADEMY varchar(200) comment '最高学历毕业院校',
    GRADUATION_DATE varchar(8) comment '最高学历毕业时间',
    DEGREE_CODE varchar(10) comment '最高学位',
    DEGREE_ACADEMY varchar(200) comment '最高学位毕业院校',
    LIVING_CONDITION varchar(10) comment '居住状况',
    MONTHLY_PAY Decimal(20,2) comment '月薪',
    ANNUAL_EARNINGS Decimal(20,2) comment '本人年收入',
    OCCUPATION_CODE varchar(6) comment '职业',
    COMPANY_TYPE varchar(10) comment '工作单位性质',
    EMPLOYER_NAME varchar(200) comment '雇主名称',
    TITLE_CODE varchar(10) comment '职称',
    CUST_APPELLATION varchar(10) comment '客户称呼',
    REMARK varchar(200) comment '备注,修改印鉴卡关联添加描述',
    INTERNAL_IND varchar(1) comment '是否为内部客户 ',
    CLIENT_INDICATOR varchar(1) comment '客户标识 ',
    SRC_UPDATED_TS timestamp comment '源系统更新时间',
    UPDATED_SYSTEM_ID varchar(10) comment '更新外部系统号',
    INVALID_DATE varchar(8) comment '失效日期'
);
alter table BAT_CIF_INDVL comment '个人客户基本信息 undefined';