drop table if exists FM_SYSTEM;
/*==============================================================*/
/* Table: FM_SYSTEM                                           */
/*==============================================================*/
create table FM_SYSTEM
(
    COY_NAME varchar(40) not null comment '银行全称',
    COY_SHORT varchar(20) not null comment '银行简称',
    RUN_DATE varchar(8) not null comment '运行日期',
    MTH_END_DATE varchar(8) not null comment '本月月末日期',
    YR_END_DATE varchar(8) not null comment '本年年末日期',
    HEAD_OFFICE_CLIENT varchar(12) comment '总行清算行内部客户',
    CAPITAL_FUNDS Decimal(17,2) comment '投资资金',
    INTER_BRANCH_IND varchar(1) not null comment '是否为内部银行',
    EBH_BRANCH varchar(6) comment '电子银行',
    LAST_RUN_DATE varchar(8) comment '上一运行日期',
    NEXT_RUN_DATE varchar(8) not null comment '下一运行日',
    AUTO_CLIENT_GEN varchar(1) not null comment '是否自动生成客户号',
    INTER_BRANCH_ACCT_HO varchar(16) comment '分行间清算科目-同业存放',
    DEFAULT_RATE_TYPE_LOCAL varchar(3) comment '默认本地汇率类型',
    DEFAULT_BRANCH varchar(8) comment '默认机构',
    EXCHANGE_RATE_VARIANCE Decimal(15,8) comment '汇率浮动百分比',
    MAIN_BRANCH_CODE varchar(50) comment '总行层级代码',
    QUR_END_DATE varchar(8) not null comment '季末日期',
    HALF_END_DATE varchar(8) not null comment '半年末日期',
    CLIENT_BLOCK_FREQ varchar(2) not null default '1Y'   comment '资料不全客户冻结周期',
    AUTO_COLL_GEN varchar(1) not null default 'Y'   comment '是否自动生成抵质押编号',
    AUTO_LOCK_BL_CLIENT varchar(1) not null default 'N'   comment '自动冻结黑名单客户',
    GL_IND varchar(1) not null default 'Y'   comment 'SYMBOLS总账分离标志 ',
    PROCESS_SPLIT_IND varchar(1) not null default 'N'   comment '批处理阶段标志',
    MULTI_CORPORATION_FLAG varchar(1) comment '是否多法人系统',
    MULTI_CORPORATION_METHOD varchar(1) comment '多法人机构间清算方式 ',
    MULTI_CORP_QUERY_ALLOW varchar(1) comment '多法人是否允许跨法人查询标志 ',
    RB_RESTRAINT_TYPE varchar(3) comment '默认存款账户限制类型 ',
    INTERNAL_RATE_CHARGE_FLAG varchar(1) comment '是否行内结售汇平盘',
    DEFAULT_CHARGE_RATE_TYPE varchar(3) comment '结售汇内部平盘汇率类型',
    DAC_IND varchar(1) comment 'DAC校验标志',
    ALLOW_BACKQRY_DAY varchar(5) comment '允许查询的历史天数',
    BATCH_MODULE varchar(2) comment '当前批处理的模块号',
    BATCH_UNIT varchar(20) comment '当前批处理的业务组编号',
    SYSTEM_PHASE varchar(3) not null default 'INP'   comment '系统所处的阶段',
    CONTINUOUS_RUN varchar(1) not null default 'Y'   comment '是否连续使用指定的数字区间标志',
    PRODUCT_30E varchar(1) not null default 'Y'   comment '是否产品版30E计算天数',
    IS_DEBUG varchar(1) default 'Y' comment '是否记录业务数据信息 ',
    IS_ERROR varchar(1) default 'Y' comment '是否记录出错时的业务数据信息',
    BATCH_DEFAULT_USER_ID varchar(30) comment '默认批处理用户',
    BATCH_CHECK_FLAG varchar(1) comment '批处理检查标志',
    CR_DR_CHECK_FLAG varchar(1) comment '借贷检查标志',
    COMPANY varchar(20) not null comment '法人',
    DEFAULT_PROFIT_CENTRE varchar(12) comment '默认利润中心',
    CLIENT_NO_STRUCTURE_TYPE varchar(3) comment '客户号结构类型',
    BASE_CCY varchar(3) comment '基础币种',
    LIMIT_CCY varchar(3) comment '限制币种',
    LOCAL_CCY varchar(3) comment '当地币种',
    REPORT_CCY varchar(3) comment '报表币种',
    NPV_GAP_TYPE varchar(3) comment '敞口类型',
    DEFAULT_RATE_TYPE varchar(3) comment '本地币种汇率类型',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    MULTI_INFO_SHARE varchar(1) comment '法人间客户信息是否共享',
    MULTI_ENABLE_SWAP varchar(1) comment '是否允许法人间交易',
    primary  key (COMPANY)
);
alter table FM_SYSTEM comment '系统业务参数表 undefined';