drop table if exists FM_TRAN_INFO_HIST;
/*==============================================================*/
/* Table: FM_TRAN_INFO_HIST                                           */
/*==============================================================*/
create table FM_TRAN_INFO_HIST
(
    TRAN_SEQ_NO varchar(50) not null comment '交易序号',
    MODULE_ID varchar(2) not null comment '业务模块',
    SOURCE_TYPE varchar(10) not null comment '渠道类型',
    TERMINAL_NO varchar(20) comment '终端ID',
    SERVER_CODE varchar(30) comment '服务代码',
    MESSAGE_TYPE varchar(4) not null comment '服务类型',
    MESSAGE_CODE varchar(6) not null comment '服务代码',
    OFFICER_ID varchar(30) not null comment '交易柜员',
    CHANNEL_SEQ_NO varchar(50) comment '渠道流水号',
    REFERENCE varchar(50) comment '交易参考号',
    PROGRAM_ID varchar(20) comment '程序ID',
    TRAN_BRANCH varchar(20) not null comment '交易机构',
    TRAN_DATE varchar(8) not null comment '交易日期',
    APPR_OFFICER_ID varchar(30) comment '复核柜员',
    APPR_DATE varchar(8) comment '复核日期',
    AUTH_OFFICER_ID varchar(30) comment '授权柜员',
    OPERATE_STATUS varchar(4) comment '业务操作状态',
    OPERATE_DESC varchar(100) comment '业务操作描述',
    BASE_ACCT_NO varchar(150) comment '账号',
    PROD_TYPE varchar(50) comment '账户类型',
    ACCT_CCY varchar(3) comment '币种',
    ACCT_SEQ_NO varchar(8) comment '子帐户序号',
    ACCT_NAME varchar(200) comment '账户名称',
    TRAN_AMT Decimal(17,2) comment '交易金额',
    TRAN_TYPE varchar(10) comment '交易类型',
    OTH_BASE_ACCT_NO varchar(150) comment '对方账号',
    OTH_PROD_TYPE varchar(50) comment '对方账户类型',
    OTH_ACCT_CCY varchar(3) comment '对方币种',
    OTH_ACCT_SEQ_NO varchar(8) comment '对方子账号',
    OTH_ACCT_NAME varchar(200) comment '对方账户名称',
    OTH_TRAN_TYPE varchar(10) comment '对方交易类型',
    SERV_AMT Decimal(17,2) comment '手续费',
    DOC_TYPE varchar(10) comment '凭证类型',
    PREFIX varchar(10) comment '凭证前缀',
    VOUCHER_START_NO varchar(50) comment '凭证起始号码',
    VOUCHER_END_NO varchar(50) comment '凭证终止号码',
    CLIENT_NO varchar(20) comment '客户号',
    CLIENT_NAME varchar(200) comment '客户名称',
    DOCUMENT_TYPE varchar(3) comment '证件类型',
    DOCUMENT_ID varchar(75) comment '证件号码',
    REVERSE_FLAG varchar(1) comment '冲正标志',
    NARRATIVE varchar(300) comment '摘要',
    PARTITION_FLAG varchar(50) comment '分区标志',
    COMMISSION_CLIENT_NAME varchar(200) comment '代办人名称',
    COMMISSION_DOC_TYPE varchar(3) comment '代办人证件类型',
    COMMISSION_DOC_ID varchar(75) comment '代办人证件号码',
    CHECK_RESULT varchar(2) comment '身份核查结果',
    RET_STATUS varchar(10) comment '返回状态',
    COMPANY varchar(20) comment '法人',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间'
);
alter table FM_TRAN_INFO_HIST comment '统一流水信息历史表 undefined';