drop table if exists FX_MB_EXCHANGE_TRAN_HIST;
/*==============================================================*/
/* Table: FX_MB_EXCHANGE_TRAN_HIST                                           */
/*==============================================================*/
create table FX_MB_EXCHANGE_TRAN_HIST
(
    SEQ_NO varchar(50) comment '序号',
    TRAN_TYPE varchar(10) comment '交易类型',
    TRAN_DATE varchar(8) comment '交易日期',
    VALUE_DATE varchar(8) comment '生效日期',
    DEPOSIT_SEQ_NO varchar(50) comment '贷方交易序号',
    DEPOSIT_INTERNAL_KEY Decimal(15) comment '贷方账户主键',
    DEPOSIT_BALANCE_TYPE varchar(2) comment '贷方余额类型 ',
    WITHDRAW_SEQ_NO varchar(50) comment '借方交易序号',
    WITHDRAW_INTERNAL_KEY Decimal(15) comment '借方账户主键',
    WITHDRAW_BALANCE_TYPE varchar(2) comment '借方余额类型 CA:现钞 TT:现汇',
    CLIENT_NO varchar(20) comment '客户号',
    CASH_SEQ_NO varchar(50) comment '现金交易序号',
    SELL_BUY_IND varchar(1) comment '买卖固定方',
    BUY_CCY varchar(3) comment '买入币种',
    BUY_AMOUNT Decimal(17,2) comment '买入金额',
    SELL_CCY varchar(3) comment '卖出币种  FM_CURRENCY.CCY',
    SELL_AMOUNT Decimal(17,2) comment '卖出金额',
    RATE_TYPE varchar(3) comment '利率类型 IRL_INT_TYPE.INT_TAX_TYPE',
    QUOTE_TYPE varchar(1) comment '报价类型 I:间接报价 D:直接报价',
    CROSS_RATE Decimal(15,8) comment '交叉汇率',
    FLOAT_RATE Decimal(15,8) comment '浮动利率',
    BUY_RATE Decimal(15,8) comment '买方汇率',
    SELL_RATE Decimal(15,8) comment '卖方汇率',
    INNER_RATE Decimal(15,8) comment '内部价',
    EXCH_RATE Decimal(15,8) comment '执行汇率',
    CROSS_RATE_ATTR varchar(30) comment '交叉汇率属性',
    BASE_RATE_TYPE varchar(3) comment '基础汇率类型',
    BASE_QUOTE_TYPE varchar(1) comment '基础报价方式',
    BASE_RATE Decimal(15,8) comment '基础汇率',
    BASE_EQUIV_AMT Decimal(17,2) comment '通过汇率换算后本币金额 ',
    CHANGE_SELL_AMOUNT Decimal(17,2) comment '找零金额',
    CHANGE_CNY_AMOUNT Decimal(17,2) comment '找零金额',
    CHANGE_SEQ_NO varchar(50) comment '找零信息 找零交易序号',
    CHANGE_RATE_TYPE varchar(3) comment '找零信息 找零汇率类型',
    CHANGE_QUOTE_TYPE varchar(1) comment '找零信息 找零汇率报价方式',
    CHANGE_RATE Decimal(15,8) comment '找零汇率',
    CHANGE_BASE_RATE Decimal(15,8) comment '找零信息',
    CHANGE_BASE_QUOTE_TYPE varchar(1) comment '找零基础汇率报价方式',
    CHANGE_BASE_RATE_TYPE varchar(3) comment '找零基础汇率类型',
    CHANGE_BASE_EQUIV_AMT Decimal(17,2) comment '找零信息',
    UNC_CROSS_RATE Decimal(15,8) comment '平盘交叉汇率',
    REMARK varchar(200) comment '备注，用来描述制卡原因，比如正常制卡，补换卡等',
    SOURCE_MODULE varchar(10) comment '模块',
    SOURCE_TYPE varchar(10) comment '渠道 FM_CHANNEL.CHANNEL',
    BRANCH varchar(20) comment '机构代码',
    PROFIT_CENTRE varchar(12) comment '利润中心 FM_PROFIT_CENTRE.PROFIT_CENTRE',
    USER_ID varchar(30) comment '交易柜员 FM_USER.USER_ID',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    TERMINAL_ID varchar(200) comment '终端标识',
    REVERSAL_TRAN_TYPE varchar(10) comment '冲正交易类型  MB_TRAN_DEF.TRAN_TYPE',
    REVERSAL_DATE varchar(8) comment '冲正日期',
    REVERSAL_USER_ID varchar(30) comment '冲正柜员',
    REVERSAL_AUTH_USER_ID varchar(30) comment '冲正授权柜员',
    APPROVAL_DATE varchar(8) comment '复核日期',
    APPR_USER_ID varchar(30) comment '复核柜员',
    APPR_AUTH_USER_ID varchar(30) comment '复核授权柜员',
    BANK_SEQ_NO varchar(50) comment '银行交易序号',
    REFERENCE varchar(50) comment '交易参考号',
    TRACE_REF_NO varchar(50),
    TRACE_REF_CODE varchar(50),
    STATUS varchar(3) comment '状态 A:有效 E:失效',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    TRAN_STATUS varchar(3) comment '状态 S:成功 F:失败',
    EXCHANGE_ITEM_CODE varchar(10) comment '结售汇项目编码',
    BASE_ACCT_NO varchar(150) comment '账号',
    ACCT_SEQ_NO varchar(8) comment '账户序列号',
    ACCT_CCY varchar(3) comment '账户币种，',
    PROD_TYPE varchar(50) comment '产品类型',
    OTH_BASE_ACCT_NO varchar(150) comment '对方帐号/卡号',
    OTH_ACCT_SEQ_NO varchar(8) comment '对方账户序列号',
    OTH_PROD_TYPE varchar(50) comment '第三方产品类型  MB_PROD_TYPE.PROD_TYPE',
    OTH_ACCT_CCY varchar(3) comment '对方账户币种  FM_CURRENCY.CCY',
    EXCHANGE_TRAN_CODE varchar(10) comment '收入方结售汇交易编码',
    PLEDGED_ACCT_NO varchar(150) comment '抵押账号',
    PLEDGED_ACCT_CCY varchar(3) comment '抵押账户币种  FM_CURRENCY.CCY',
    PLEDGED_ACCT_TYPE varchar(3) comment '抵押账户类型',
    PLEDGED_AMT Decimal(17,2) comment '限制金额',
    EXCHANGE_TYPE varchar(2) comment '结售汇类型 01:一般贸易 02:服务贸易 03:资本项目 04:对私 05:外汇交易市场平补 06:银行自身 07:其他',
    IS_INDIVIDUAL varchar(1) comment '是否个体客',
    EX_TYPE varchar(1)
);
alter table FX_MB_EXCHANGE_TRAN_HIST comment '结售汇交易流水表 undefined';