drop table if exists GL_SYSTEM;
/*==============================================================*/
/* Table: GL_SYSTEM                                           */
/*==============================================================*/
create table GL_SYSTEM
(
    SEQ_NO varchar(50) not null comment '序号',
    HIST_PERIOD_NO varchar(5) comment '总账历史保存期',
    HIST_PERIOD_TYPE varchar(1) comment '总账历史保存期类型',
    MAX_BACKDATE_DAY varchar(5) comment '最大倒起息天数',
    MAX_FUTUREDATE_DAY varchar(5) comment '最大将来起息天数',
    RETAIN_EARNINGS varchar(20) not null comment '净利润科目 取值AC_SUBJECT',
    INT_PAYABLE varchar(20) comment '应付利息科目 取值AC_SUBJECT',
    INT_RECEIVABLE varchar(20) comment '应收利息科目 取值AC_SUBJECT',
    OS_CLOSE_BAL varchar(20) comment '销户挂账科目 取值AC_SUBJECT',
    ACCT_HIST_PERIOD_NO varchar(5) comment '总账账户月末余额信息保留期限(月)',
    AUTO_INT_ACCT_CREATION varchar(1) comment '是否自动创建内部帐户 Y 是 N 否',
    INT_ACCT_TYPE varchar(1) comment '利息帐户类型 I 内部 C 客户级',
    TAX_ACCT_TYPE varchar(1) comment '税率帐户类型 I 内部 C 客户级',
    DEFAULT_RATE_TYPE varchar(3) comment '默认汇率类型 取值FM_RATE_TYPE.RATE_TYPE',
    REVAL_BY_POST varchar(1) comment '损益评估',
    IS_BATCH_FINISHED varchar(1) not null comment '是否批处理完成 Y/N',
    TAX_FREQ varchar(2) comment '营业税缴税频率 取值FM_PERIOD_FREQ.PERIOD_FREQ',
    NEXT_CYCLE_DATE varchar(8) comment '营业税下个缴税日期',
    PREV_CYCLE_DATE varchar(8) comment '营业税上个缴税日期',
    LAST_POSTING_RETENTION_DATE varchar(8) comment '历史数据起始日期',
    INTER_ACCTG_BK varchar(16) comment '跨帐套过渡科目',
    TWO_BOOK varchar(1) not null comment '跨帐套标志',
    OS_CLOSE_IND varchar(1) not null comment '允许非零账户销户标志 Y 允许 N 不允许',
    AUTO_REF varchar(1) comment '是否自动产生交易参考号 Y 自动生成 N 不自动生成',
    REF_PREFIX varchar(3) comment '交易参考号前缀 默认GL',
    BO_IND varchar(1) comment '多法人多级清算分录联机或批处理处理标志 O-联机产生 B-批处理产生',
    BATCH_CONS_IND varchar(1) comment '是否合并清算流水 Y-根据轧差后的清算流水生成会计分录  N-根据原始清算流水生成会计分录',
    MULTISETTLE_IND varchar(1) comment '是否合并清算分录 Y-合并 N-不合并',
    COMPANY varchar(20) not null comment '法人代码',
    LAST_RUN_DATE varchar(8) not null comment '上一运行日期',
    RUN_DATE varchar(8) not null comment '运行日期',
    NEXT_RUN_DATE varchar(8) not null comment '下一运行日期',
    PROFIT_CENTRE varchar(12) not null comment '利润中心',
    LOCAL_CCY varchar(3) not null comment '当地币种',
    CCY_CTRL_ACCT varchar(20) comment '币种控制帐户',
    SUSP_ASSET_ACCT varchar(20) not null comment '资产类型挂账科目',
    SUSP_LIAB_ACCT varchar(20) not null comment '负债类挂账科目',
    SUSP_CONT_ASSET varchar(20) not null comment '表外过度科目-资产类',
    SUSP_CONT_LIAB varchar(20) not null comment '表外过度科目-负债类',
    SUSP_SETTLE_ASSET varchar(20) not null comment '结算挂账科目-资产',
    SUSP_SETTLE_LIAB varchar(20) not null comment '结算挂账科目-负债',
    GL_CASH_CODE varchar(20) comment '其他应付款科目',
    BASE_CCY varchar(3) not null comment '基础币种',
    DEFAULT_CHARGE_RATE_TYPE varchar(3) not null comment '结售汇内部平盘汇率类型',
    DEFAULT_BRANCH varchar(8) not null comment '默认机构',
    MUTI_SETTLE_MODE varchar(1) comment '清算模式 0 -0级清算 1-多级清算',
    YEAR_EARNINGS varchar(20) comment '年终利润 科目 AC_SUBJECT.SUBJECT_CODE',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    primary  key (SEQ_NO)
);
alter table GL_SYSTEM comment '总帐系统参数表 undefined';