drop table if exists MB_BATCH_OPEN_DETAILS;
/*==============================================================*/
/* Table: MB_BATCH_OPEN_DETAILS                                           */
/*==============================================================*/
create table MB_BATCH_OPEN_DETAILS
(
    BATCH_NO varchar(50) not null comment '批处理号',
    SEQ_NO varchar(50) not null comment '序号',
    DOCUMENT_TYPE varchar(3) comment '证件类型 ',
    DOCUMENT_ID varchar(75) comment '证件号码',
    ISS_COUNTRY varchar(3) comment '发证国家 ',
    EXPIRY_DATE varchar(8) comment '到期日期',
    CH_CLIENT_NAME varchar(200) comment '关联方中文名称',
    CLIENT_NAME varchar(200) comment '客户名称',
    SEX varchar(1) comment '客户性别',
    OCCUPATION_CODE varchar(6) comment '职业参数表',
    PHONE_NO varchar(50) comment '固定电话',
    MOBILE_NO varchar(50) comment '手机号码',
    EMAIL varchar(50) comment '电子邮件',
    LOCATION varchar(50) comment '客户地址',
    WITHDRAWAL_TYPE varchar(1) comment '支取方式 ',
    SOC_SEC_NO varchar(50) comment '客户社保参保号码',
    COPR_NAME varchar(200) comment '单位名称',
    COPR_SOC_SEC_NO varchar(50) comment '单位社保参保号码',
    GUARDIAN varchar(50) comment '监护人名称',
    GUARDIANSHIP varchar(50) comment '和监护人关系',
    GUARDIAN_DOC_ID varchar(50) comment '监护人身份证号',
    GUARDIAN_PHONE varchar(50) comment '监护人联系电话',
    BUSINESS_TYPE varchar(50) comment '业务类型',
    TRAN_STATUS varchar(3) comment '状态 ',
    ERROR_DESC varchar(4000) comment '未生成分录原因',
    CARD_ACCT_NO varchar(150) comment '卡号账号,如果成功,记录生成的账号或者卡号',
    CLIENT_NO varchar(20) comment '客户号',
    DOC_TYPE varchar(10) comment '凭证类型',
    VOUCHER_NO varchar(50) comment '凭证号',
    PREFIX varchar(10) comment '前缀',
    TRAN_AMT Decimal(17,2) comment '交易金额',
    PRINT_CNT varchar(5) comment '打印次数',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    OPEN_CCY varchar(3) comment '币种 ',
    OPEN_BRANCH varchar(20) comment '开立机构',
    PROD_TYPE varchar(50) comment '产品类型',
    CARD_P_FLAG varchar(1) comment '卡/折标志',
    FROM_CARD_NO varchar(50) comment '失败数量',
    TO_CARD_NO varchar(50) comment '终止卡号',
    CLIENT_TYPE varchar(3) comment '客户类型',
    CATEGORY_TYPE varchar(3) comment '客户细类',
    CONTACT_TYPE varchar(3) comment '联系类型',
    ALL_DRA_IND varchar(1) comment '通兑标志',
    ALL_DEP_IND varchar(1) comment '通存标志',
    ACCT_NATURE varchar(4) comment '账户属性 ',
    GET_TYPE varchar(10) comment '批量开卡领取方式',
    OPEN_DATE varchar(8) comment '开立日期',
    REASON_CODE varchar(6) comment '账户用途',
    primary  key (BATCH_NO,SEQ_NO)
);
alter table MB_BATCH_OPEN_DETAILS comment '批量开立信息明细登记簿 undefined';