drop table if exists MB_BATCH_DRW_DETAILS;
/*==============================================================*/
/* Table: MB_BATCH_DRW_DETAILS                                           */
/*==============================================================*/
create table MB_BATCH_DRW_DETAILS
(
    BATCH_NO varchar(50) comment '批处理号',
    SEQ_NO varchar(50) comment '序号',
    TRAN_TYPE varchar(10) comment '交易类型',
    CONTRACT_NO varchar(50) comment '合同号',
    PROD_TYPE varchar(50) comment '产品类型',
    BASE_ACCT_NO varchar(150) comment '账号',
    CMISLOAN_NO varchar(50) comment '借据号',
    BRANCH varchar(20) comment '机构代码',
    CLIENT_NO varchar(20) comment '客户号',
    CCY varchar(3) comment '币种',
    ORIG_LOAN_AMT Decimal(17,2) comment '合同金额',
    START_DATE varchar(8) comment '生效日期',
    END_DATE varchar(8) comment '终止日期',
    DD_AMT Decimal(17,2) comment '发放金额',
    DD_DATE varchar(8) comment '发放日期',
    ANALYSIS varchar(6) comment '分析类型',
    GUARANTY_STYLE varchar(6) comment '担保方式',
    SCHED_MODE varchar(3) comment '计划方式  MB_SCHED_MODE.SCHED_MODE',
    CYCLE_FREQ varchar(2) comment '结息周期',
    NEXT_CYCLE_DATE varchar(8) comment '下一结息日',
    INT_DAY varchar(2) comment '结息日',
    PRE_REPAY_DEAL varchar(1) comment '还款计划变更方式 A:变额不变期 T:变期不变额',
    AUTO_SETTLE varchar(1) comment '是否自动结算',
    REVOLVE_YN varchar(1) comment '是否循环贷款',
    HUNTING_STATUS varchar(1) comment '持续扣款标志 Y:是 N:否',
    ANYTIME_REC varchar(1) comment '随借随还标志',
    INT_APPL_TYPE varchar(1) comment '利率启用方式 MB_ATTR_VALUE.INT_APPL_TYPE',
    ROLL_FREQ varchar(2) comment '利率变更周期',
    ROLL_DATE varchar(8) comment '下一个利率变更日期 ',
    ROLL_DAY varchar(2) comment '下一个利率变更日 ',
    INT_RATE Decimal(15,8) comment '支取利率',
    ODP_RATE Decimal(15,8) comment '罚息利率',
    ODI_RATE Decimal(15,8) comment '复利利率',
    ODODP_RATE Decimal(15,8) comment '罚息复利利率',
    ODODI_RATE Decimal(15,8) comment '复利的复利利率',
    YEAR_BASIS varchar(3) comment '年基准天数 360天 365天',
    MONTH_BASIS varchar(3) comment '月基准 ACT:实际天数 30D:每月30天',
    SETTLE_PAY_BASE_ACCT_NO varchar(50) comment '结算账户',
    SETTLE_PAY_ACCT_SEQ_NO varchar(8) comment '结算账户序列号',
    SETTLE_REC_BASE_ACCT_NO varchar(50) comment '自动回收账户账号',
    SETTLE_REC_ACCT_SEQ_NO varchar(8) comment '自动回收账户序列号',
    SETTLE_WTR_BASE_ACCT_NO varchar(50) comment '委托存款账户账号',
    SETTLE_WTR_ACCT_SEQ_NO varchar(8) comment '委托存款账户序列号',
    SETTLE_WTS_BASE_ACCT_NO varchar(50) comment '委托结算账户账号',
    SETTLE_WTS_ACCT_SEQ_NO varchar(8) comment '委托结算账户序列号',
    ERROR_DESC varchar(4000) comment '未生成分录原因',
    TRAN_STATUS varchar(3) comment '状态 S:成功 F:失败',
    TRAN_TIMESTAMP varchar(17) comment '时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    NORMAL_INT_TYPE varchar(3) comment '正常利率利率类型',
    ODP_INT_TYPE varchar(3) comment '罚息利率类型',
    ODI_INT_TYPE varchar(3) comment '复利利率类型',
    ODODP_INT_TYPE varchar(3) comment '罚息的复利利率类型',
    ODODI_INT_TYPE varchar(3) comment '复利的复利利率类型',
    NORMAL_CALC_BY_INT varchar(1) comment '正常利率是否随执行利率浮动',
    ODP_CALC_BY_INT varchar(1) comment '罚息利率是否随执行利率浮动',
    ODI_CALC_BY_INT varchar(1) comment '复利利率是否随执行利率浮动',
    ODODP_CALC_BY_INT varchar(1) comment '罚息的复利利率是否随执行利率浮动 ',
    ODODI_CALC_BY_INT varchar(1) comment '复利的复利利率是否随执行利率浮动',
    INT_ACTUAL_RATE Decimal(15,8) comment '正常利息行内利率',
    ODP_ACTUAL_RATE Decimal(15,8) comment '罚息行内利率',
    ODI_ACTUAL_RATE Decimal(15,8) comment '复利行内利率',
    ODODP_ACTUAL_RATE Decimal(15,8) comment '罚息的复利行内利率',
    ODODI_ACTUAL_RATE Decimal(15,8) comment '复利的复利行内利率'
);
alter table MB_BATCH_DRW_DETAILS comment '批量发放明细表 undefined';