drop table if exists MB_BATCH_OPEN_DCT_DETAILS;
/*==============================================================*/
/* Table: MB_BATCH_OPEN_DCT_DETAILS                                           */
/*==============================================================*/
create table MB_BATCH_OPEN_DCT_DETAILS
(
    CONTRAST_BAT_NO varchar(50) not null comment '批次号',
    SEQ_NO varchar(50) not null comment '序号',
    DOCUMENT_TYPE varchar(3) comment '证件类型 ',
    DOCUMENT_ID varchar(75) comment '证件号码',
    ISS_COUNTRY varchar(3) comment '发证国家',
    EXPIRY_DATE varchar(8) comment '到期日期',
    CH_CLIENT_NAME varchar(200) comment '关联方中文名称',
    CLIENT_NAME varchar(200) comment '客户名称',
    SEX varchar(1) comment '客户性别 FM_REF_CODE.SEX',
    OCCUPATION_CODE varchar(6) comment '职业',
    PHONE_NO varchar(50) comment '固定电话',
    MOBILE_NO varchar(50) comment '手机号码',
    EMAIL varchar(50) comment '电子邮件',
    LOCATION varchar(50) comment '客户地址',
    WITHDRAWAL_TYPE varchar(1) comment '支取方式 ',
    STATUS varchar(3) comment '状态',
    ERROR_DESC varchar(4000) comment '未生成分录原因',
    CARD_ACCT_NO varchar(150) comment '卡号账号,如果成功,记录生成的账号或者卡号',
    CLIENT_NO varchar(20) comment '客户号',
    DOC_TYPE varchar(10) comment '凭证类型',
    PREFIX varchar(10) comment '前缀',
    VOUCHER_NO varchar(50) comment '凭证号',
    TRAN_AMT Decimal(17,2) comment '交易金额',
    TERM_PERIOD varchar(5) comment '敞口类型',
    TERM_TYPE varchar(1) comment '存期类型',
    PROD_TYPE varchar(50) comment '产品类型',
    AUTO_RENEW_ROLLOVER varchar(1) comment '是否自动转存',
    TRAN_TYPE varchar(10) comment '交易类型',
    CARD_P_FLAG varchar(1) comment '卡/折标志',
    OPEN_CCY varchar(3) comment '币种 ',
    OPEN_BRANCH varchar(20) comment '开立机构',
    PRINT_CNT varchar(5) comment '打印次数',
    CONTACT_ADRESS varchar(200) comment '公司联系地址',
    CONTACT_TYPE varchar(3) comment '联系类型',
    CLIENT_DOCUMENT_TYPE varchar(20) comment '公司客户类型细分',
    CLIENT_TYPE varchar(3) comment '客户类型',
    OTH_ACCT_NO varchar(150) comment '其他账号',
    COPR_NAME varchar(200) comment '单位名称',
    OTH_ACCT_NAME varchar(200) comment '对方户名',
    OTH_DOC_TYPE varchar(10) comment '凭证类型（转出） ',
    OTH_PREFIX varchar(10) comment '对方票据前缀',
    OTH_ACCT_SEQ_NO varchar(8) comment '对方账户序列号',
    OTH_VOUCHER_NO varchar(50) comment '对方票据号码',
    SIGN_DATE varchar(8) comment '登记时间',
    OTH_PROD_TYPE varchar(50) comment '第三方产品类型',
    OTH_ACCT_CCY varchar(3) comment '对方账户币种 ',
    OTH_BAL_TYPE varchar(2) comment '对方余额类型',
    BAL_TYPE varchar(2) comment '余额类型',
    EFFECT_DATE varchar(8) comment '生效日期',
    CASH_ITEM varchar(4) comment '现金项目',
    TRAN_TIMESTAMP varchar(17) comment '时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ACCT_NATURE varchar(4) comment '账户属性 ',
    primary  key (CONTRAST_BAT_NO,SEQ_NO)
);
alter table MB_BATCH_OPEN_DCT_DETAILS comment '批量开立存单客户登记表 undefined';