drop table if exists MB_BATCH_OPEN;
/*==============================================================*/
/* Table: MB_BATCH_OPEN                                           */
/*==============================================================*/
create table MB_BATCH_OPEN
(
    CONTRAST_BAT_NO varchar(50) not null comment '批次号',
    OPEN_CLASS varchar(3) not null comment '批量开立业务分类',
    CONTRAST_DESC varchar(250) comment '描次描述',
    OPEN_TYPE varchar(3) comment '批量开立方式',
    FILE_NAME varchar(500) comment '文件名',
    FILE_PATH varchar(512) comment '文件路径',
    TOTAL_NUM varchar(10) comment '总数量',
    TOTAL_AMT Decimal(17,2) comment '总金额',
    OPEN_DATE varchar(8) comment '开立日期',
    OPEN_BRANCH varchar(20) comment '申请开立机构',
    CARD_P_FLAG varchar(1) comment '卡/折标志：C-卡 P-折',
    PROD_TYPE varchar(50) comment '批量开户产品类型',
    OPEN_CCY varchar(3) comment '批量开户币种',
    GET_TYPE varchar(10) comment '批量开卡领取方式',
    COPR_NAME varchar(200) comment '单位名称',
    WITHDRAWAL_TYPE varchar(1) comment '支取方式',
    FROM_CARD_NO varchar(50) comment '失败数量',
    TO_CARD_NO varchar(50) comment '终止卡号',
    CONTRAST_BAT_STATUS varchar(1) comment '批次状态',
    SUCC_NUM varchar(10) comment '成功数量',
    FAIL_NUM varchar(10) comment '失败数量',
    ERROR_DESC varchar(4000) comment '错误描述',
    SERVER_IP varchar(50) comment '后台服务IP',
    BEGIN_TIME varchar(30) comment '开始时间',
    END_TIME varchar(30) comment '完成时间',
    APPR_FLAG varchar(1) comment '复核标志',
    APPR_USER_ID varchar(30) comment '复核柜员',
    AUTH_FLAG varchar(1) comment '授权标志',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    BRANCH_ID varchar(20) comment '执行机构',
    COMPANY varchar(20) comment '法人',
    DEST_BRANCH_NO varchar(6) comment '目标节点编号',
    MAC_VALUE varchar(50) comment '传输密押',
    PROGRAM_ID varchar(20) comment '交易屏幕标识号',
    REFERENCE varchar(50) comment '交易参考号',
    RUN_DATE varchar(8) comment '运行日期',
    SEQ_NO varchar(50) comment '交易流水号',
    SOURCE_BRANCH_NO varchar(6) comment '源节点编号',
    SOURCE_TYPE varchar(10) comment '渠道类型',
    SYSTEM_ID varchar(20) comment '系统ID',
    THREAD_NO varchar(512) comment '线程编号',
    TRAN_DATE varchar(8) comment '交易日期',
    TRAN_MODE varchar(10) comment '交易模式',
    TRAN_TIMESTAMP varchar(17) comment '运行时间',
    USER_ID varchar(30) comment '柜员',
    USER_LANG varchar(20) comment '柜员语言',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    CLIENT_TYPE varchar(3) not null comment '客户类型',
    CATEGORY_TYPE varchar(3) not null comment '客户细分类型',
    CONTACT_TYPE varchar(3) not null comment '联系类型',
    primary  key (CONTRAST_BAT_NO)
);
alter table MB_BATCH_OPEN comment '批量开立信息登记簿 undefined';