TRUNCATE TABLE cif_salutation;
INSERT INTO cif_salutation (SALUTATION, SALUTATION_DESC, GENDER_FLAG, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('B', 'MR先生', 'M', 'DCITS', NULL, NULL);
INSERT INTO cif_salutation (SALUTATION, SALUTATION_DESC, GENDER_FLAG, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('D', 'MS女士', 'F', 'DCITS', NULL, NULL);

COMMIT;
