TRUNCATE TABLE cif_client_type;
INSERT INTO cif_client_type (CLIENT_TYPE, CLIENT_TYPE_DESC, IS_INDIVIDUAL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('10', '个人', 'Y', 'DCITS', NULL, NULL);
INSERT INTO cif_client_type (CLIENT_TYPE, CLIENT_TYPE_DESC, IS_INDIVIDUAL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('20', '公司', 'N', 'DCITS', NULL, NULL);
INSERT INTO cif_client_type (CLIENT_TYPE, CLIENT_TYPE_DESC, IS_INDIVIDUAL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('30', '同业', 'N', 'DCITS', NULL, NULL);
INSERT INTO cif_client_type (CLIENT_TYPE, CLIENT_TYPE_DESC, IS_INDIVIDUAL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('40', '内部', 'N', 'DCITS', NULL, NULL);
INSERT INTO cif_client_type (CLIENT_TYPE, CLIENT_TYPE_DESC, IS_INDIVIDUAL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('90', '其他', 'N', 'DCITS', NULL, NULL);

COMMIT;
