TRUNCATE TABLE cif_qualification;
INSERT INTO cif_qualification (QUALIFICATION, QUALIFICATION_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('0', '无', 'DCITS', NULL, NULL);
INSERT INTO cif_qualification (QUALIFICATION, QUALIFICATION_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1', '高级', 'DCITS', NULL, NULL);
INSERT INTO cif_qualification (QUALIFICATION, QUALIFICATION_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('2', '中级', 'DCITS', NULL, NULL);
INSERT INTO cif_qualification (QUALIFICATION, QUALIFICATION_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3', '初级', 'DCITS', NULL, NULL);
INSERT INTO cif_qualification (QUALIFICATION, QUALIFICATION_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('9', '未知', 'DCITS', NULL, NULL);

COMMIT;
