TRUNCATE TABLE cif_occupation;
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('0', '国家机关、党群组织、企业、事业单位负责人', 'L', NULL, NULL, NULL);
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1', '专业技术人员', 'L', NULL, NULL, NULL);
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3', '办事人员和有关人员', 'L', NULL, NULL, NULL);
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4', '商业、服务业人员', 'L', NULL, NULL, NULL);
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('5', '农、林、牧、渔、水利业生产人员', 'L', NULL, NULL, NULL);
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('6', '生产、运输设备操作人员及有关人员', 'L', NULL, NULL, NULL);
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('X', '军人', 'L', NULL, NULL, NULL);
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('Y', '不便分类的其他从业人员', 'L', NULL, NULL, NULL);
INSERT INTO cif_occupation (OCCUPATION_CODE, OCCUPATION_DESC, RISK_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('Z', '未知', 'L', NULL, NULL, NULL);

COMMIT;
