TRUNCATE TABLE cif_class_level;
INSERT INTO cif_class_level (CLASS_LEVEL, CLASS_LEVEL_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('01', 'Pass正常', NULL, NULL, NULL);
INSERT INTO cif_class_level (CLASS_LEVEL, CLASS_LEVEL_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('02', 'Special Mention关注', NULL, NULL, NULL);
INSERT INTO cif_class_level (CLASS_LEVEL, CLASS_LEVEL_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('03', 'Substandard次级', NULL, NULL, NULL);
INSERT INTO cif_class_level (CLASS_LEVEL, CLASS_LEVEL_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('04', 'Doubtful可疑', NULL, NULL, NULL);
INSERT INTO cif_class_level (CLASS_LEVEL, CLASS_LEVEL_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('05', 'Loss损失', NULL, NULL, NULL);

COMMIT;
