TRUNCATE TABLE cif_cr_rating;
INSERT INTO cif_cr_rating (CR_RATING, CR_RATING_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('001', '1级', NULL, NULL, NULL);
INSERT INTO cif_cr_rating (CR_RATING, CR_RATING_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('002', '2级', NULL, NULL, NULL);
INSERT INTO cif_cr_rating (CR_RATING, CR_RATING_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('003', '3级', NULL, NULL, NULL);
INSERT INTO cif_cr_rating (CR_RATING, CR_RATING_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('004', '4级', NULL, NULL, NULL);
INSERT INTO cif_cr_rating (CR_RATING, CR_RATING_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('005', '5级', NULL, NULL, NULL);

COMMIT;
