TRUNCATE TABLE cif_client_status;
INSERT INTO cif_client_status (CLIENT_STATUS, CLIENT_STATUS_DESC, BAD_CLIENT_IND, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('01', '潜在客户', 'N', 'DCITS', NULL, NULL);
INSERT INTO cif_client_status (CLIENT_STATUS, CLIENT_STATUS_DESC, BAD_CLIENT_IND, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('02', '正式客户-活跃客户', 'N', 'DCITS', NULL, NULL);
INSERT INTO cif_client_status (CLIENT_STATUS, CLIENT_STATUS_DESC, BAD_CLIENT_IND, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('03', '正式客户-非活跃客户', 'N', 'DCITS', NULL, NULL);
INSERT INTO cif_client_status (CLIENT_STATUS, CLIENT_STATUS_DESC, BAD_CLIENT_IND, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('04', '正式客户-保全客户', 'N', 'DCITS', NULL, NULL);
INSERT INTO cif_client_status (CLIENT_STATUS, CLIENT_STATUS_DESC, BAD_CLIENT_IND, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('05', '退出客户', 'N', 'DCITS', NULL, NULL);
INSERT INTO cif_client_status (CLIENT_STATUS, CLIENT_STATUS_DESC, BAD_CLIENT_IND, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('99', '其他', 'N', 'DCITS', NULL, NULL);

COMMIT;
