TRUNCATE TABLE cif_resident_type;
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1', '自置', 'DCITS', NULL, NULL);
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('2', '按揭', 'DCITS', NULL, NULL);
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3', '亲属楼宇', 'DCITS', NULL, NULL);
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4', '集体宿舍', 'DCITS', NULL, NULL);
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('5', '租房', 'DCITS', NULL, NULL);
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('6', '共有住宅', 'DCITS', NULL, NULL);
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('7', '其他', 'DCITS', NULL, NULL);
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('8', '单位分配', 'DCITS', NULL, NULL);
INSERT INTO cif_resident_type (RESIDENT_TYPE, RESIDENT_TYPE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('9', '未知', 'DCITS', '20180125182429', '1516875869');

COMMIT;
