TRUNCATE TABLE tb_cash_sign_reson;
INSERT INTO tb_cash_sign_reson (SHTG_TYPE, SHTG_ID, SHTG_DESC, OVER_TRAN_TYPE, SHORT_TRAN_TYPE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CASHFROMTO', 'C', '现金', 'CK02', 'DK02', NULL, NULL, NULL);
INSERT INTO tb_cash_sign_reson (SHTG_TYPE, SHTG_ID, SHTG_DESC, OVER_TRAN_TYPE, SHORT_TRAN_TYPE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CASHFROMTO', 'G', '总账账户', 'CK03', 'DK03', NULL, NULL, NULL);
INSERT INTO tb_cash_sign_reson (SHTG_TYPE, SHTG_ID, SHTG_DESC, OVER_TRAN_TYPE, SHORT_TRAN_TYPE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CASHFROMTO', 'R', '活期账户', 'CK01', 'DK01', NULL, NULL, NULL);
INSERT INTO tb_cash_sign_reson (SHTG_TYPE, SHTG_ID, SHTG_DESC, OVER_TRAN_TYPE, SHORT_TRAN_TYPE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('REASONID', '1', '柜员操作错误', '2119', '2113', NULL, NULL, NULL);
INSERT INTO tb_cash_sign_reson (SHTG_TYPE, SHTG_ID, SHTG_DESC, OVER_TRAN_TYPE, SHORT_TRAN_TYPE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('REASONID', '2', '利息尾数长款', '2119', '2113', NULL, NULL, NULL);
INSERT INTO tb_cash_sign_reson (SHTG_TYPE, SHTG_ID, SHTG_DESC, OVER_TRAN_TYPE, SHORT_TRAN_TYPE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('REASONID', '5', 'ATM差错', '2119', '2113', NULL, NULL, NULL);
INSERT INTO tb_cash_sign_reson (SHTG_TYPE, SHTG_ID, SHTG_DESC, OVER_TRAN_TYPE, SHORT_TRAN_TYPE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('REASONID', '6', '清分差错', '2119', '2113', NULL, NULL, NULL);

COMMIT;
