TRUNCATE TABLE tb_unit_def;
INSERT INTO tb_unit_def (UNIT_CODE, UNIT_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1', '张', NULL, NULL);
INSERT INTO tb_unit_def (UNIT_CODE, UNIT_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('2', '捆', NULL, NULL);
INSERT INTO tb_unit_def (UNIT_CODE, UNIT_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3', '本', NULL, NULL);
INSERT INTO tb_unit_def (UNIT_CODE, UNIT_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4', '份', NULL, NULL);

COMMIT;
