TRUNCATE TABLE appr_letter_param;
INSERT INTO appr_letter_param (PARA_KEY, PARA_VALUE, PARA_DESC, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('1003', '1003', '活期支取', NULL, NULL);
INSERT INTO appr_letter_param (PARA_KEY, PARA_VALUE, PARA_DESC, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('4183', '4183', '行内转账存入(支票)', NULL, NULL);
INSERT INTO appr_letter_param (PARA_KEY, PARA_VALUE, PARA_DESC, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('4180', '4180', '行内转账支取(支票)', NULL, NULL);
INSERT INTO appr_letter_param (PARA_KEY, PARA_VALUE, PARA_DESC, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('4186', '4186', '行内转账支取(非支票)', NULL, NULL);
INSERT INTO appr_letter_param (PARA_KEY, PARA_VALUE, PARA_DESC, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('1000', '1000', '活期存入', NULL, NULL);
INSERT INTO appr_letter_param (PARA_KEY, PARA_VALUE, PARA_DESC, TRAN_TIME, TRAN_TIMESTAMP) VALUES ('4189', '4189', '行内转账存入(非支票)', NULL, NULL);

COMMIT;
