TRUNCATE TABLE mb_analysis1;
INSERT INTO mb_analysis1 (ANALYSIS1, ANALYSIS1_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1', '正常贷款', NULL, NULL);
INSERT INTO mb_analysis1 (ANALYSIS1, ANALYSIS1_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('2', '关注贷款', NULL, NULL);
INSERT INTO mb_analysis1 (ANALYSIS1, ANALYSIS1_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3', '次级贷款', NULL, NULL);
INSERT INTO mb_analysis1 (ANALYSIS1, ANALYSIS1_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4', '可疑贷款', NULL, NULL);
INSERT INTO mb_analysis1 (ANALYSIS1, ANALYSIS1_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('5', '损失贷款', NULL, NULL);

COMMIT;
