TRUNCATE TABLE mb_acct_close_reason;
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1', '账户清理', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('10', '撤并、解散、宣告破产或关闭', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('11', '转同业其他银行', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('12', '久悬户', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('13', '账户到期', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('14', '项目结束（专用户、特定用途的一般户）', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('15', '不方便', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('16', '其他', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('2', '搬迁', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3', '代发解除', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4', '代扣解除', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('5', '理财解除', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('6', '贷款结清', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('7', '验资撤销（指无资金入账，不需出具验资后续资料直接撤销）', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('8', '验资完毕（指资金入账，按照相关手续办理验资户的销户）', NULL, NULL, NULL);
INSERT INTO mb_acct_close_reason (REASON_CODE, REASON_CODE_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('9', '注销或吊销营业执照', NULL, NULL, NULL);

COMMIT;
