TRUNCATE TABLE mb_collat_type;
INSERT INTO mb_collat_type (COLLAT_TYPE, COLLAT_TYPE_DESC) VALUES ('CL01', '房');
INSERT INTO mb_collat_type (COLLAT_TYPE, COLLAT_TYPE_DESC) VALUES ('CL02', '车');
INSERT INTO mb_collat_type (COLLAT_TYPE, COLLAT_TYPE_DESC) VALUES ('CL03', '存单');

COMMIT;
