TRUNCATE TABLE mb_certificate_type;
INSERT INTO mb_certificate_type (CERTIFICATE_TYPE, CERTIFICATE_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('6', '其他', 'DCITS', NULL, NULL, NULL, NULL);
INSERT INTO mb_certificate_type (CERTIFICATE_TYPE, CERTIFICATE_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('5', '行车执照', 'DCITS', NULL, NULL, NULL, NULL);
INSERT INTO mb_certificate_type (CERTIFICATE_TYPE, CERTIFICATE_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('4', '不动产证', 'DCITS', NULL, NULL, NULL, NULL);
INSERT INTO mb_certificate_type (CERTIFICATE_TYPE, CERTIFICATE_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('3', '契税证', 'DCITS', NULL, NULL, NULL, NULL);
INSERT INTO mb_certificate_type (CERTIFICATE_TYPE, CERTIFICATE_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('2', '土地证', 'DCITS', NULL, NULL, NULL, NULL);
INSERT INTO mb_certificate_type (CERTIFICATE_TYPE, CERTIFICATE_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('1', '房产证', 'DCITS', NULL, NULL, NULL, NULL);

COMMIT;
