TRUNCATE TABLE mb_dep_wtd_tran_type;
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('2128', '2125', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4183', '4180', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4189', '2203', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4189', '4186', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4198', '4196', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4283', '4280', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4289', '4286', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4304', '4306', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4306', '4304', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4322', '4320', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('4389', '4386', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AC05', 'AC03', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('FX04', 'FX05', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('FX09', 'FX10', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('FX15', 'FX16', NULL, NULL);
INSERT INTO mb_dep_wtd_tran_type (DEP_TRAN_TYPE, WTD_TRAN_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('QD03', 'QD01', NULL, NULL);

COMMIT;
