TRUNCATE TABLE mb_materials_type;
INSERT INTO mb_materials_type (MATERIALS_TYPE, MATERIALS_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('4', '其他物资类', 'DCITS', NULL, NULL, NULL, NULL);
INSERT INTO mb_materials_type (MATERIALS_TYPE, MATERIALS_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('3', '股权类', 'DCITS', NULL, NULL, NULL, NULL);
INSERT INTO mb_materials_type (MATERIALS_TYPE, MATERIALS_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('2', '土地类', 'DCITS', NULL, NULL, NULL, NULL);
INSERT INTO mb_materials_type (MATERIALS_TYPE, MATERIALS_TYPE_DESC, COMPANY, TRAN_DATE, USER_ID, LAST_CHANGE_DATE, LAST_CHANGE_USER_ID) VALUES ('1', '房产类', 'DCITS', NULL, NULL, NULL, NULL);

COMMIT;
