TRUNCATE TABLE mb_open_ctl;
INSERT INTO mb_open_ctl (CLIENT_TYPE, CTRL_ATTR, CTRL_VALUE, QUANTITY, DEAL_FLOW, TRAN_TIMESTAMP, TRAN_TIME, COMPANY) VALUES ('01', 'D', 'CRD', '4', 'A', NULL, NULL, NULL);
INSERT INTO mb_open_ctl (CLIENT_TYPE, CTRL_ATTR, CTRL_VALUE, QUANTITY, DEAL_FLOW, TRAN_TIMESTAMP, TRAN_TIME, COMPANY) VALUES ('01', 'ACCT_CLASS', '1', '1', 'B', NULL, NULL, NULL);
INSERT INTO mb_open_ctl (CLIENT_TYPE, CTRL_ATTR, CTRL_VALUE, QUANTITY, DEAL_FLOW, TRAN_TIMESTAMP, TRAN_TIME, COMPANY) VALUES ('01', 'ACCT_CLASS', '2', '5', 'B', NULL, NULL, NULL);
INSERT INTO mb_open_ctl (CLIENT_TYPE, CTRL_ATTR, CTRL_VALUE, QUANTITY, DEAL_FLOW, TRAN_TIMESTAMP, TRAN_TIME, COMPANY) VALUES ('01', 'ACCT_CLASS', '3', '5', 'B', NULL, NULL, NULL);

COMMIT;
