TRUNCATE TABLE mb_prod_group;
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB009', 'RB003', '1', 'Y', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB009', 'RB005', '2', 'N', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB009', 'RB006', '3', 'N', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB009', 'RB008', '4', 'N', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB010', 'RB001', '1', 'Y', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB010', 'RB002', '2', 'N', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB010', 'RB003', '3', 'N', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB010', 'RB004', '4', 'N', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB010', 'RB005', '5', 'N', 'DCITS', NULL, NULL, NULL);
INSERT INTO mb_prod_group (PROD_TYPE, PROD_SUB_TYPE, SEQ_NO, DEFAULT_PROD, COMPANY, TRAN_TIMESTAMP, TRAN_TIME, RATIO) VALUES ('RB010', 'RB006', '6', 'N', 'DCITS', NULL, NULL, NULL);

COMMIT;
