TRUNCATE TABLE mb_prod_preference;
INSERT INTO mb_prod_preference (PROD_TYPE, PREFERENCE_TYPE, PREFERENCE_VALUE, PREFERENCE_PERCENT_RATE, PREFERENCE_SPREAD_RATE, PREFERENCE_FIXED_RATE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('230001', 'CACL_AMT_DIST', '100000', '0.9', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mb_prod_preference (PROD_TYPE, PREFERENCE_TYPE, PREFERENCE_VALUE, PREFERENCE_PERCENT_RATE, PREFERENCE_SPREAD_RATE, PREFERENCE_FIXED_RATE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('230001', 'CACL_AMT_DIST', '200000', '0.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mb_prod_preference (PROD_TYPE, PREFERENCE_TYPE, PREFERENCE_VALUE, PREFERENCE_PERCENT_RATE, PREFERENCE_SPREAD_RATE, PREFERENCE_FIXED_RATE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('230002', 'AGG_BAL_CTD', '200000', NULL, '-2', NULL, 'DCITS', NULL, NULL);
INSERT INTO mb_prod_preference (PROD_TYPE, PREFERENCE_TYPE, PREFERENCE_VALUE, PREFERENCE_PERCENT_RATE, PREFERENCE_SPREAD_RATE, PREFERENCE_FIXED_RATE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('230002', 'AGG_BAL_CTD', '100000', NULL, '-1', NULL, 'DCITS', NULL, NULL);

COMMIT;
