TRUNCATE TABLE mb_pcp_parameter;
INSERT INTO mb_pcp_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('PCP_PROD_TYPE', '160001', '资金池产品类型', NULL, NULL, NULL);
INSERT INTO mb_pcp_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('PCP_GROUP_STOREY', '3', '资金池账户组层数', NULL, NULL, NULL);

COMMIT;
