TRUNCATE TABLE fm_bank_hierarchy;
INSERT INTO fm_bank_hierarchy (HIERARCHY_CODE, HIERARCHY_NAME, HIERARCHY_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1', '总行', '0', 'DCITS', NULL, NULL);
INSERT INTO fm_bank_hierarchy (HIERARCHY_CODE, HIERARCHY_NAME, HIERARCHY_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('2', '分行', '1', 'DCITS', NULL, NULL);
INSERT INTO fm_bank_hierarchy (HIERARCHY_CODE, HIERARCHY_NAME, HIERARCHY_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3', '支行', '2', 'DCITS', NULL, NULL);

COMMIT;
