TRUNCATE TABLE fm_business_parameter;
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('LG_RES_TYPE', '003', '保函限制', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('TPREC_TRAN_TYPE', 'PREC', '封包后回收', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('TRANSFER_RES_TYPE', '004', '账户资金圈存（系统用）', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('TRREC_TRAN_TYPE', 'TREC', '表外贷款表内入账', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('POST_TRAN_TYPE', 'POST', '抵债资产入账', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('PROA_TRAN_TYPE', 'PROA', '抵债资产拨备计提', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('OWN_TRAN_TYPE', 'OWN', '抵债资产自用处置', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('SALE_TRAN_TYPE', 'SALE', '抵债资产变卖处置', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('MAR_TRAN_TYPE', 'MAR', '抵债资产损毁处置', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('RENT_TRAN_TYPE', 'RENT', '抵债资产租赁处置', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('DEBT_ASSET_SETTLE', '4186', '转账交易类型', NULL, NULL, NULL);
INSERT INTO fm_business_parameter (PARA_KEY, PARA_VALUE, PARA_DESC, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CASH_SETTLE', '1000', '现金存入', NULL, NULL, NULL);

COMMIT;
