TRUNCATE TABLE fm_bank;
INSERT INTO fm_bank (BANK_CODE, BANK_ID, BANK_NAME, BANK_TYPE, STATUS, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1', '1234', 'yinhang', 'B', 'A', NULL, NULL, NULL);

COMMIT;
