TRUNCATE TABLE fm_company;
INSERT INTO fm_company (COMPANY, COMPANY_NAME, HEAD_OFFICE_CODE, COMPANY_CLIENT_NO, SYSTEM_PHASE, MULTI_CORP_QUERY_ALLOW, TRAN_TIMESTAMP, TRAN_TIME, ROUTER_KEY) VALUES ('DCITS', '神州银行', '9999', '9999', NULL, 'Y', NULL, NULL, NULL);
INSERT INTO fm_company (COMPANY, COMPANY_NAME, HEAD_OFFICE_CODE, COMPANY_CLIENT_NO, SYSTEM_PHASE, MULTI_CORP_QUERY_ALLOW, TRAN_TIMESTAMP, TRAN_TIME, ROUTER_KEY) VALUES ('DCBANK', 'DC银行', '6000', '6000', NULL, 'Y', NULL, NULL, NULL);

COMMIT;
