TRUNCATE TABLE fm_cash_inout_category;
INSERT INTO fm_cash_inout_category (CLIENT_BRANCH_TYPE, CLIENT_TYPE, CATEGORY_TYPE, PROD_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('B', '30', '301', '310001', NULL, NULL);
INSERT INTO fm_cash_inout_category (CLIENT_BRANCH_TYPE, CLIENT_TYPE, CATEGORY_TYPE, PROD_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('S', '30', NULL, '310004', NULL, NULL);

COMMIT;
