TRUNCATE TABLE fm_default_rate_type;
INSERT INTO fm_default_rate_type (TRAN_SCENE, RATE_TYPE, TRAN_SCENC_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CLIENT_RATE_TYPE', 'CTR', '客户汇率', NULL, NULL);
INSERT INTO fm_default_rate_type (TRAN_SCENE, RATE_TYPE, TRAN_SCENC_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('HBD_RATE_TYPE', 'HBD', '货币对汇率', NULL, NULL);
INSERT INTO fm_default_rate_type (TRAN_SCENE, RATE_TYPE, TRAN_SCENC_DESC, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('UNC_RATE_TYPE', 'ZSL', '平盘汇率', NULL, NULL);

COMMIT;
