TRUNCATE TABLE fm_ex_unchange_branch;
INSERT INTO fm_ex_unchange_branch (BRANCH, UNCHANGE_BRANCH, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1001', '9999', NULL, NULL);
INSERT INTO fm_ex_unchange_branch (BRANCH, UNCHANGE_BRANCH, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1002', '9999', NULL, NULL);

COMMIT;
