TRUNCATE TABLE fm_fta_def;
INSERT INTO fm_fta_def (FTA_CODE, FTA_DESC, TRAN_TIME, TRAN_TIMESTAMP, COUNTRY, STATE, CITY, FTA_TYPE, FTA_NATURE, FTE_FLAG, FTI_FLAG, FTN_FLAG, FTU_FLAG, FTF_FLAG) VALUES ('SHFTA', '上海自贸区', NULL, NULL, 'CHN', '31', '310000', '贸工结合', '商业自由区', 'SFTE', 'SFTI', 'SFIN', 'SFTU', 'SFTF');
INSERT INTO fm_fta_def (FTA_CODE, FTA_DESC, TRAN_TIME, TRAN_TIMESTAMP, COUNTRY, STATE, CITY, FTA_TYPE, FTA_NATURE, FTE_FLAG, FTI_FLAG, FTN_FLAG, FTU_FLAG, FTF_FLAG) VALUES ('TJFTA', '天津自贸区', NULL, NULL, 'CHN', '12', '120000', '转口集散型', '工业自由区', 'TFTE', 'TFTI', 'TFIN', 'TFTU', 'TFTF');

COMMIT;
