TRUNCATE TABLE fm_password_failure_times;
INSERT INTO fm_password_failure_times (PASSWORD_TYPE, CHANNEL, MAX_FAILUER_TIMES, RESET_IND, BRANCH, LAST_CHANGE_OFFICER, LAST_CHANGE_DATE, LAST_CHANGE_TIME, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('MA', 'ALL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20171106133157', '1509946317');
INSERT INTO fm_password_failure_times (PASSWORD_TYPE, CHANNEL, MAX_FAILUER_TIMES, RESET_IND, BRANCH, LAST_CHANGE_OFFICER, LAST_CHANGE_DATE, LAST_CHANGE_TIME, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('QY', 'ALL', '10', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fm_password_failure_times (PASSWORD_TYPE, CHANNEL, MAX_FAILUER_TIMES, RESET_IND, BRANCH, LAST_CHANGE_OFFICER, LAST_CHANGE_DATE, LAST_CHANGE_TIME, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('WD', 'ALL', '10', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT;
