TRUNCATE TABLE fm_profit_centre;
INSERT INTO fm_profit_centre (PROFIT_CENTRE, PROFIT_CENTRE_DESC, PROFIT_CENTRE_DESC_EN, PROFIT_CENTRE_TYPE, PROFIT_CENTRE_LEVEL, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('99', '利润中心', '利润中心', 'S', '2', NULL, NULL, NULL);

COMMIT;
