TRUNCATE TABLE fm_region;
INSERT INTO fm_region (REGION, REGION_DESC, INTERNAL_CODE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AF', '非洲', '0', NULL, NULL, NULL);
INSERT INTO fm_region (REGION, REGION_DESC, INTERNAL_CODE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AN', '南极洲', '0', NULL, NULL, NULL);
INSERT INTO fm_region (REGION, REGION_DESC, INTERNAL_CODE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AS', '亚洲', '1', NULL, NULL, NULL);
INSERT INTO fm_region (REGION, REGION_DESC, INTERNAL_CODE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('DY', '东亚', '0', NULL, NULL, NULL);
INSERT INTO fm_region (REGION, REGION_DESC, INTERNAL_CODE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('EU', '欧洲', '0', NULL, NULL, NULL);
INSERT INTO fm_region (REGION, REGION_DESC, INTERNAL_CODE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('NA', '北美洲', '0', NULL, NULL, NULL);
INSERT INTO fm_region (REGION, REGION_DESC, INTERNAL_CODE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('OC', '大洋洲', '0', NULL, NULL, NULL);
INSERT INTO fm_region (REGION, REGION_DESC, INTERNAL_CODE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('SA', '南美洲', '0', NULL, NULL, NULL);

COMMIT;
