TRUNCATE TABLE fm_seq_type;
INSERT INTO fm_seq_type (SEQ_TYPE, START_NO, END_NO, BRANCH_RESET, PROD_TYPE_RESET, CCY_RESET, IS_INDVL_RESET, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('001', '1', '999999999', 'N', 'Y', 'N', 'N', NULL, NULL, NULL);
INSERT INTO fm_seq_type (SEQ_TYPE, START_NO, END_NO, BRANCH_RESET, PROD_TYPE_RESET, CCY_RESET, IS_INDVL_RESET, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('002', '1', '999999999', 'N', 'N', 'N', 'N', NULL, NULL, NULL);

COMMIT;
