TRUNCATE TABLE fm_structure_param;
INSERT INTO fm_structure_param (STRUCTURE_TYPE, PARAM_TYPE, LENGTH, START_POS, END_POS, PADDING_CHAR, SEQ_TYPE, STRING_VALUE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AC', 'CD', '1', '17', '17', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fm_structure_param (STRUCTURE_TYPE, PARAM_TYPE, LENGTH, START_POS, END_POS, PADDING_CHAR, SEQ_TYPE, STRING_VALUE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AC', 'PT', '6', '1', '6', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fm_structure_param (STRUCTURE_TYPE, PARAM_TYPE, LENGTH, START_POS, END_POS, PADDING_CHAR, SEQ_TYPE, STRING_VALUE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AC', 'SN', '10', '7', '16', '0', '001', NULL, NULL, NULL, NULL);
INSERT INTO fm_structure_param (STRUCTURE_TYPE, PARAM_TYPE, LENGTH, START_POS, END_POS, PADDING_CHAR, SEQ_TYPE, STRING_VALUE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CD', 'CB', '6', '1', '6', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fm_structure_param (STRUCTURE_TYPE, PARAM_TYPE, LENGTH, START_POS, END_POS, PADDING_CHAR, SEQ_TYPE, STRING_VALUE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CD', 'CD', '1', '18', '18', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fm_structure_param (STRUCTURE_TYPE, PARAM_TYPE, LENGTH, START_POS, END_POS, PADDING_CHAR, SEQ_TYPE, STRING_VALUE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CD', 'CT', '3', '7', '9', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fm_structure_param (STRUCTURE_TYPE, PARAM_TYPE, LENGTH, START_POS, END_POS, PADDING_CHAR, SEQ_TYPE, STRING_VALUE, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CD', 'SN', '8', '10', '17', '0', '002', NULL, NULL, NULL, NULL);

COMMIT;
