TRUNCATE TABLE fm_structure_type;
INSERT INTO fm_structure_type (STRUCTURE_TYPE, STRUCTURE_ATTR, STRUCTURE_DESC, STRUCTURE_LENGTH, STRUCTURE_CLASS, DELIMITER_IND, RESTRICTED_DELIMITER, COMPLETE_IND, CHECK_DIGIT_FORMULA, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('AC', 'AN', '账号规则', '16', 'AN', 'N', NULL, 'Y', 'JYW', NULL, NULL, NULL);
INSERT INTO fm_structure_type (STRUCTURE_TYPE, STRUCTURE_ATTR, STRUCTURE_DESC, STRUCTURE_LENGTH, STRUCTURE_CLASS, DELIMITER_IND, RESTRICTED_DELIMITER, COMPLETE_IND, CHECK_DIGIT_FORMULA, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('CD', 'AN', '借记卡卡号规则', '18', 'AN', 'N', NULL, 'Y', 'JYW', NULL, NULL, NULL);

COMMIT;
