TRUNCATE TABLE fm_sub_branch_tbl;
INSERT INTO fm_sub_branch_tbl (SUB_BRANCH_CODE, SUB_BRANCH_NAME, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('01', '西安分行', 'DCITS', NULL, NULL);
INSERT INTO fm_sub_branch_tbl (SUB_BRANCH_CODE, SUB_BRANCH_NAME, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('02', '北京分行', 'DCITS', NULL, NULL);
INSERT INTO fm_sub_branch_tbl (SUB_BRANCH_CODE, SUB_BRANCH_NAME, COMPANY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('03', '上海分行', 'DCITS', NULL, NULL);

COMMIT;
