TRUNCATE TABLE tr_rule_trans;
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1001', 'FM144', '快速建立客户信息', '0', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1001', 'FM144D', '对私客户信息维护', '1', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1001', 'RB211A', '个人活期开户', '2', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1001', 'CL0101', '贷款开立', '3', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('1001', 'RB31', '活期存入', '4', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3001', '009002', '日终现金碰库', '0', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3001', '009003', '日终凭证碰库', '1', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3001', '009004', '日终扎账单打印', '2', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3001', '009006', '网点日终', '4', NULL, NULL);
INSERT INTO tr_rule_trans (RULE_CODE, PROGRAM_ID, TRAN_DESC, SEQ_NO, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('3002', 'RB31', '活期存入', '0', NULL, NULL);

COMMIT;
