drop table if exists APPR_LETTER_TRAN_HIST;
/*==============================================================*/
/* Table: APPR_LETTER_TRAN_HIST                                           */
/*==============================================================*/
create table APPR_LETTER_TRAN_HIST
(
    SEQ_NO varchar(50) not null comment '序号',
    INTERNAL_KEY Decimal(15) comment '帐户主键',
    TRAN_DATE varchar(8) not null comment '交易日期',
    TRAN_TYPE varchar(10) comment '交易类型',
    EVENT_TYPE varchar(50) comment '事件类型',
    CCY varchar(3) comment '币种',
    CR_DR_MAINT_IND varchar(1) comment '借贷标志',
    TRAN_AMT Decimal(17,2) comment '交易金额',
    BRANCH varchar(20) comment '机构代码',
    SOURCE_TYPE varchar(10) comment '渠道类型 ',
    TERMINAL_ID varchar(200) comment '终端标识',
    USER_ID varchar(30) comment '使用柜员',
    TRAN_CATEGORY varchar(1) comment '交易种类',
    BANK_SEQ_NO varchar(50) comment '银行交易序号',
    EFFECT_DATE varchar(8) comment '生效日期',
    REVERSAL_TRAN_TYPE varchar(10) comment '冲正交易类型',
    REVERSAL_DATE varchar(8) comment '冲正日期',
    PREVIOUS_BAL_AMT Decimal(17,2) comment '交易前余额',
    ACTUAL_BAL_AMT Decimal(17,2) comment '实际余额',
    BASE_ACCT_NO varchar(150) comment '账号',
    ACCT_SEQ_NO varchar(8) comment '账户序列号',
    ACCT_CCY varchar(3) comment '账户币种',
    PROD_TYPE varchar(50) comment '产品类型 ',
    ACCT_BRANCH varchar(20) comment '账户开户行',
    GL_CODE varchar(20) comment '科目',
    ACCT_DESC varchar(150) comment '账户描述',
    TRACE_ID varchar(50) comment '跟踪ID',
    NARRATIVE varchar(300) comment '摘要',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    APPR_USER_ID varchar(30) comment '复核柜员',
    TRAN_DESC varchar(100) comment '交易描述',
    TRAN_TIMESTAMP varchar(17) comment '时间戳',
    CASH_ITEM varchar(4) comment '现金项目',
    TRAN_NOTE varchar(100) comment '交易附言',
    TRAN_STATUS varchar(3) comment '客户交易状态 ',
    OTH_SEQ_NO varchar(50) comment '对方交易流水号',
    OTH_INTERNAL_KEY Decimal(15) comment '转账时对方账户标识符',
    OTH_BRANCH varchar(20) comment '对方账户开户机构',
    OTH_BANK_NAME varchar(200) comment '对方银行名称',
    OTH_BANK_CODE varchar(20) comment '其他行代码',
    OTH_BASE_ACCT_NO varchar(150) comment '对方帐号/卡号',
    OTH_ACCT_SEQ_NO varchar(8) comment '对方账户序列号',
    OTH_PROD_TYPE varchar(50) comment '第三方产品类型',
    OTH_ACCT_CCY varchar(3) comment '对方账户币种',
    OTH_ACCT_DESC varchar(150) comment '对方账户名称',
    OTH_REFERENCE varchar(50) comment '对方交易参考号',
    SERV_CHARGE varchar(1) comment '服务费标识',
    SORT_PRIORITY varchar(5) comment '优先级',
    APPR_LETTER_NO varchar(30) comment '核准件编号',
    APPR_TYPE varchar(2) comment '核准件类型',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    primary  key (SEQ_NO)
);
alter table APPR_LETTER_TRAN_HIST comment '核准件交易流水表 undefined';