drop table if exists DC_PRECONTRACT_INFO;
/*==============================================================*/
/* Table: DC_PRECONTRACT_INFO                                           */
/*==============================================================*/
create table DC_PRECONTRACT_INFO
(
    PRECONTRACT_NO varchar(12) not null comment '编号',
    CLIENT_NO varchar(20) not null comment '客户号',
    CH_CLIENT_NAME varchar(200) comment '关联方中文名称',
    CLIENT_NAME varchar(200) comment '客户名称',
    DOCUMENT_TYPE varchar(3) comment '证件类型 ',
    DOCUMENT_ID varchar(75) comment '证件号码',
    ISS_COUNTRY varchar(3) comment '发证国家',
    PRECONTRACT_OPEN_DATE varchar(8) comment '预约开户日期',
    PRECONTRACT_DATE varchar(8) comment '预约登记日期',
    PROD_TYPE varchar(50) comment '产品类型',
    STAGE_CODE varchar(50) comment '期次代码',
    ISSUE_START_DATE varchar(8) comment '发行起始日期',
    ISSUE_END_DATE varchar(8) comment '发行终止日期',
    PRECONTRACT_AMT_BRANCH varchar(20) comment '可用金额配置机构',
    ISSUE_AMT Decimal(17,2) comment '期次发行额度',
    PRECONTRACT_CCY varchar(3) comment '预约币种',
    PRECONTRACT_AMT Decimal(17,2) comment '预约金额',
    INTERNAL_KEY Decimal(15) comment '帐户主键',
    RESTRAINT_SEQ_NO varchar(50) comment '账户冻结限制编号',
    PRECONTRACT_BRANCH varchar(20) comment '预约 / 认购机构',
    SOURCE_TYPE varchar(10) comment '渠道 ',
    PRECONTRACT_STATUS varchar(2) comment '预约/认购状态 ',
    DEL_USER_ID varchar(30) comment '删除柜员',
    DEL_AUTH_USER_ID varchar(30) comment '删除授权柜员',
    DEL_DATE varchar(8) comment '删除日期',
    DEL_REASON varchar(200) comment '删除原因',
    OPEN_DATE varchar(8) comment '开立日期',
    FAILURE_REASON varchar(4000) comment '失败原因',
    USER_ID varchar(30) comment '交易柜员',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    REFERENCE varchar(50) comment '交易参考号',
    SEQ_NO varchar(50) comment '序号',
    INT_TYPE varchar(3) comment '利率类型',
    ACTUAL_RATE Decimal(15,8) comment '行内利率',
    FLOAT_RATE Decimal(15,8) comment '浮动利率',
    REAL_RATE Decimal(15,8) comment '执行利率',
    NARRATIVE varchar(300) comment '摘要，开户时的账号用途，销户时的销户原因',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    TRAN_TIMESTAMP varchar(17) comment '时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    PRINT_USER_ID varchar(30) comment '打印柜员',
    PRINT_DATE varchar(8) comment '打印日期',
    INT_CALC_TYPE varchar(50) comment '计息方式 ',
    PRECONTRACT_STYPE varchar(1) comment ' 预约 / 认购方式',
    STAGE_PROD_CLASS varchar(4) comment '期次产品分类'
);