drop table if exists DC_PRECONTRACT;
/*==============================================================*/
/* Table: DC_PRECONTRACT                                           */
/*==============================================================*/
create table DC_PRECONTRACT
(
    PRECONTRACT_NO varchar(12) not null comment '编号',
    CLIENT_NO varchar(20) comment '客户号',
    PRECONTRACT_TYPE varchar(1) comment '预约登记的账户类型  ',
    PRECONTRACT_DATE varchar(8) comment '预约登记日期',
    PROD_TYPE varchar(50) comment '产品类型',
    ISSUE_YEAR varchar(4) comment '发行年度',
    STAGE_CODE varchar(50) comment '期次代码',
    ISSUE_START_DATE varchar(8) comment '发行起始日期',
    ISSUE_END_DATE varchar(8) comment '发行终止日期',
    ISSUE_AMT Decimal(17,2) comment '期次发行额度',
    PRECONTRACT_CCY varchar(3) comment '预约币种 ',
    PRECONTRACT_AMT Decimal(17,2) comment '预约金额',
    SEQ_NO varchar(50) comment '序号',
    INT_TYPE varchar(3) comment '利率类型',
    ACTUAL_RATE Decimal(15,8) comment '行内利率',
    FLOAT_RATE Decimal(15,8) comment '浮动利率',
    REAL_RATE Decimal(15,8) comment '执行利率',
    INTERNAL_KEY Decimal(15) comment '大额存单账户标识符',
    RESTRAINT_SEQ_NO varchar(50) comment '冻结编号',
    SOURCE_TYPE varchar(10) comment '渠道 ',
    PRECONTRACT_STATUS varchar(2) comment '预约状态    ',
    DEL_USER_ID varchar(30) comment '删除柜员',
    DEL_AUTH_USER_ID varchar(30) comment '删除授权柜员',
    DEL_DATE varchar(8) comment '删除日期',
    DEL_REASON varchar(200) comment '删除原因',
    OPEN_DATE varchar(8) comment '开立日期',
    FAILURE_REASON varchar(4000) comment '失败原因',
    USER_ID varchar(30) comment '交易柜员 ',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    REFERENCE varchar(50) comment '交易参考号',
    NARRATIVE varchar(300) comment '摘要，开户时的账号用途，销户时的销户原因',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    TRAN_TIMESTAMP varchar(17) comment '时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    VOUCHER_NO varchar(50) comment '凭证号',
    PRINT_CNT varchar(5) comment '打印次数',
    CHANNEL varchar(20) comment '渠道类型',
    PRECONTRACT_OPEN_DATE varchar(8) comment '预约开户日期',
    AUTO_SETTLE_FLAG  varchar(1) comment '自动结清标志 ',
    PRECONTRACT_BRANCH varchar(20) comment '预约 / 认购机构',
    INT_CALC_TYPE varchar(50) comment '计息方式 ',
    BASE_ACCT_NO varchar(150) comment '大额存单账号',
    ACCT_SEQ_NO varchar(8) comment '大额存单账户序列号',
    CCY varchar(3) comment '大额存单账户币种',
    ACCT_NAME varchar(200) comment '大额存单账户名称',
    OTH_ACCT_SEQ_NO varchar(8) comment '资金来源账户序列号',
    OTH_PROD_TYPE varchar(50) comment '资金来源账户产品类型',
    OTH_CCY varchar(3) comment '资金来源账户币种',
    OTH_BASE_ACCT_NO varchar(150) comment '资金来源账户账号',
    OTH_INTERNAL_KEY Decimal(15) comment '资金来源账户标识符',
    STAGE_PROD_CLASS varchar(4) comment '期次产品分类',
    primary  key (PRECONTRACT_NO)
);
alter table DC_PRECONTRACT comment '大额存单登记表 undefined';