drop table if exists IRL_INT_SPLIT;
/*==============================================================*/
/* Table: IRL_INT_SPLIT                                           */
/*==============================================================*/
create table IRL_INT_SPLIT
(
    SYSTEM_ID varchar(20) not null comment '系统ID',
    INTERNAL_KEY Decimal(15) not null comment '帐户主键',
    START_DATE varchar(8) not null comment '生效日期',
    END_DATE varchar(8) comment '终止日期',
    INT_CLASS varchar(20) not null comment '利息分类',
    ACCT_NO varchar(150) comment '账号',
    PROD_TYPE varchar(50) comment '产品类型',
    EVENT_TYPE varchar(50) comment '事件类型',
    BRANCH varchar(20) comment '机构代码',
    SOURCE_TYPE varchar(10) comment '渠道 ',
    CCY varchar(3) comment '币种',
    INT_CALC_BAL varchar(3) comment '计息方式',
    CLIENT_NO varchar(20) comment '客户号',
    CR_RATING varchar(4) comment '客户等级 ',
    IRL_GENE_STR varchar(500) comment '利率因子',
    INT_AMT Decimal(17,2) comment '计提金额',
    CUR_INT_ACCRUED Decimal(17,2) comment '当期累计计提',
    CUR_INT_ADJ Decimal(17,2) comment '当期累计调整',
    CUR_TAX_ACCRUED Decimal(17,2) comment '当期累计利息税',
    TAX_TYPE varchar(3) comment '税率类型',
    TAX_RATE Decimal(15,8) comment '税率',
    PRE_INT_ACCRUED Decimal(17,2) comment '期初累计计提',
    AFTER_INT_ACCRUED Decimal(17,2) comment '期末累计计提',
    PRE_INT_ADJ Decimal(17,2) comment '期初累计调整',
    AFTER_INT_ADJ Decimal(17,2) comment '期末累计调整',
    PRE_TAX_ACCRUED Decimal(17,2) comment '期初累计利息税',
    AFTER_TAX_ACCRUED Decimal(17,2) comment '期末累计利息税',
    COMPANY varchar(20) comment '法人代码',
    MONTH_BASIS varchar(3) comment '月基准 ',
    YEAR_BASIS varchar(3) comment '年基准天数 360天 365天',
    INT_TYPE varchar(3) comment '利率类型',
    ACTUAL_RATE Decimal(15,8) comment '行内利率',
    FLOAT_RATE Decimal(15,8) comment '浮动利率',
    REAL_RATE Decimal(15,8) comment '执行利率',
    ACCT_SPREAD_RATE Decimal(15,8) comment '分户级浮动百分点',
    ACCT_PERCENT_RATE Decimal(5,2) comment '分户浮动百分比',
    ACCT_FIXED_RATE Decimal(15,8) comment '分户级固定利率',
    AGREE_CHANGE_TYPE varchar(1) comment '协议变动方式',
    AGREE_FIXED_RATE Decimal(15,8) comment '协议固定利率',
    AGREE_PERCENT_RATE Decimal(5,2) comment '协议浮动百分比',
    AGREE_SPREAD_RATE Decimal(15,8) comment '协议浮动百分点',
    SPLIT_RATE_FLAG varchar(1) comment '利率分段标志',
    AFTER_INT_ACCRUED_DIFF Decimal(15,10) comment ' 期末计提差额',
    PRE_INT_ACCRUED_DIFF Decimal(15,10) comment '期初计提差额',
    AGREE_REDUCE_AMT Decimal(38,2) comment '协议优惠金额',
    TD_LAST_ACCR_DATE varchar(8) comment '当期上一计提日',
    TD_ACCR_INT_DAY varchar(2) comment '计提起始日期',
    TD_INT_NUM_DAYS varchar(5) comment '当期累计计息天数',
    CALC_BEGIN_DATE varchar(8) comment '利息计算起始日',
    TD_END_ACCR_DATE varchar(8) comment '计提结束日期',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    primary  key (SYSTEM_ID,INTERNAL_KEY,START_DATE,INT_CLASS)
);
alter table IRL_INT_SPLIT comment '分户分段信息表 undefined';