drop table if exists IRL_CAPT_INFO;
/*==============================================================*/
/* Table: IRL_CAPT_INFO                                           */
/*==============================================================*/
create table IRL_CAPT_INFO
(
    IRL_SEQ_NO varchar(50) not null comment '序号  ',
    SYSTEM_ID varchar(20) comment '系统ID',
    INTERNAL_KEY Decimal(15) not null comment '帐户主键',
    CAPT_DATE varchar(8) not null comment '结息日期',
    INT_CLASS varchar(20) not null comment '利息分类',
    ACCT_NO varchar(150) not null comment '账号',
    PROD_TYPE varchar(50) not null comment '产品类型',
    BRANCH varchar(20) not null comment '机构代码',
    SOURCE_TYPE varchar(10) comment '渠道',
    CCY varchar(3) not null comment '币种',
    CLIENT_NO varchar(20) not null comment '客户号',
    INT_POSTED Decimal(17,2) comment '累计结息利息税',
    INT_POSTED_CTD Decimal(17,2) comment '当次结息金额',
    INT_ADJ Decimal(17,2) comment '累计计提调整',
    INT_ACCRUED Decimal(17,2) comment '结息周期内累计计提金额',
    TAX_POSTED_CTD Decimal(17,2) comment '结息日结息利息税',
    TAX_POSTED Decimal(17,2) comment '利息税累计金额',
    TRAN_SOURCE varchar(6) not null comment '交易发起方',
    TAX_TYPE varchar(3) comment '税率类型',
    TAX_RATE Decimal(15,8) comment '税率',
    INT_TYPE varchar(3) comment '利率类型',
    ACTUAL_RATE Decimal(15,8) comment '行内利率',
    FLOAT_RATE Decimal(15,8) comment '浮动利率',
    REAL_RATE Decimal(15,8) comment '执行利率',
    PROFIT_CENTRE varchar(12) comment '利润中心',
    SOURCE_MODULE varchar(10) comment '模块',
    BUSINESS_UNIT varchar(10) comment '帐套',
    CLIENT_TYPE varchar(3) comment '客户类型',
    REFERENCE varchar(50) comment '交易参考号',
    REMARK varchar(200) comment '备注',
    REVERSAL varchar(1) comment '冲正标志',
    PAY_INT Decimal(17,2) comment '前付息金额',
    COMPANY varchar(20) comment '法人代码',
    ACCOUNTING_STATUS varchar(3) comment '核算状态',
    GL_POSTED varchar(1) comment '过账标志',
    PAY_INT_BAL Decimal(17,2) comment '前付息（结息）余额',
    TRAN_STATUS varchar(3) comment '交易状态',
    ACCT_SPREAD_RATE Decimal(15,8) comment '分户级浮动百分点',
    ACCT_PERCENT_RATE Decimal(5,2) comment '分户浮动百分比',
    ACCT_FIXED_RATE Decimal(15,8) comment '分户级固定利率',
    AGREE_CHANGE_TYPE varchar(1) comment '协议变动方式',
    AGREE_FIXED_RATE Decimal(15,8) comment '协议固定利率',
    AGREE_PERCENT_RATE Decimal(5,2) comment '协议浮动百分比',
    AGREE_SPREAD_RATE Decimal(15,8) comment '协议浮动百分点',
    SPLIT_RATE_FLAG varchar(1) comment '利率分段标志',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    YEAR_BASIS varchar(3) comment '年基准天数',
    START_DATE varchar(8) comment '生效日期',
    INT_AMT Decimal(17,2) comment '利息金额',
    DAYS varchar(5) comment '天数',
    primary  key (IRL_SEQ_NO)
);
alter table IRL_CAPT_INFO comment '分户结息流水表 undefined';