drop table if exists IRL_ACCT_INT;
/*==============================================================*/
/* Table: IRL_ACCT_INT                                           */
/*==============================================================*/
create table IRL_ACCT_INT
(
    IRL_INTERNAL_KEY varchar(50) not null comment '账户键值',
    INT_CLASS varchar(20) not null comment '利息分类 IRL_INT_ROLL.INT_CLASS',
    AGG Decimal(38,2) not null comment '积数',
    INT_AMT Decimal(17,2) comment '利息金额',
    INT_START_DATE varchar(8) comment '开户起息日',
    INT_IND varchar(1) comment '是否计息 Y:是 N:否',
    INT_TYPE varchar(3) comment '利率类型 IRL_INT_TYPE.INT_TAX_TYPE',
    ACTUAL_RATE Decimal(15,8) comment '行内利率',
    FLOAT_RATE Decimal(15,8) comment '浮动利率',
    REAL_RATE Decimal(15,8) comment '执行利率',
    ACCT_SPREAD_RATE Decimal(15,8) comment '分户级浮动百分点',
    ACCT_PERCENT_RATE Decimal(5,2) comment '分户浮动百分比',
    ACCT_FIXED_RATE Decimal(15,8) comment '分户级固定利率',
    INT_APPL_TYPE varchar(1) comment '利率启用方式 MB_ATTR_VALUE.INT_APPL_TYPE',
    NEXT_ROLL_DATE varchar(8) comment '下一个利率变更日期',
    LAST_ROLL_DATE varchar(8) comment '上一个利率变更日期  如果利率启用方式为R时录入',
    ROLL_FREQ varchar(2) comment '利率变更周期',
    ROLL_DAY varchar(2) comment '下一个利率变更日 ',
    CYCLE_PERIOD_FREQ varchar(2) comment '结息周期  FM_PERIOD_FREQ.PERIOD_FREQ',
    CYCLE_INT_DAY varchar(50) comment '结息日',
    NEXT_CYCLE_DATE varchar(8) comment '下一结息日',
    LAST_CYCLE_DATE varchar(8) comment '上一结息日',
    ACCR_PERIOD_FREQ varchar(2) comment '计提周期  FM_PERIOD_FREQ.PERIOD_FREQ',
    ACCR_INT_DAY varchar(2) comment '计提日',
    NEXT_ACCR_DATE varchar(8) comment '下一计提日期',
    LAST_ACCR_DATE varchar(8) comment '上一计提日期',
    INT_ACCRUED Decimal(17,2) comment '累计计提利息（结息周期内累计计提金额）',
    INT_ACCRUED_DIFF Decimal(15,10) comment '计提金额差额',
    INT_ADJ_CTD Decimal(17,2) comment '计提日利息调整',
    INT_ADJ Decimal(17,2) comment '利息调整(累计)',
    INT_ACCRUED_CTD Decimal(17,2) comment '计提日计提利息',
    INT_ACCRUED_CALC_CTD Decimal(25,10) comment '计提日计提原金额（实际计算金额）',
    INT_POSTED Decimal(17,2) comment '结息利息金额（累计金额）',
    INT_POSTED_CTD Decimal(17,2) comment '结息日利息金额',
    TAX_TYPE varchar(3) comment '税率类型  IRL_INT_TYPE.INT_TAX_TYPE',
    TAX_RATE Decimal(15,8) comment '税率',
    TAX_ACCRUED_CTD Decimal(17,2) comment '计提日利息税',
    TAX_ACCRUED Decimal(17,2) comment '结息周期内利息税累计金额',
    TAX_POSTED_CTD Decimal(17,2) comment '结息日利息税',
    TAX_POSTED Decimal(17,2) comment '利息税累计金额',
    INT_ACCRUED_T Decimal(17,2) comment '存期计提累计利息',
    COMPANY varchar(20) comment '法人代码',
    TAX_ACCRUED_DIFF Decimal(15,10) comment '利息税差额',
    TAX_ACCRUED_CALC_CTD Decimal(25,10) comment '计提日利息税原金额（实际计算金额）',
    MONTH_BASIS varchar(3) comment '月基准 ACT:实际天数 30D:每月30天',
    YEAR_BASIS varchar(3) comment '年基准天数 360天 365天',
    PAY_INT_BAL Decimal(17,2) comment '前付息（结息）余额',
    IS_CYCLE varchar(1) comment '是否结息 Y:是 N:否',
    IS_RETRY varchar(1) comment '是否重算 Y:是 N:否',
    AGREE_AGG Decimal(38,2) comment '协议积数',
    AGREE_POST Decimal(17,2) comment '协议利息 ',
    NP_PRI varchar(1) comment '本金转非应计标志',
    NP_INT varchar(1) comment '利息转非应计标志',
    AGREE_REDUCE_AMT Decimal(38,2) comment '协议优惠金额',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    primary  key (IRL_INTERNAL_KEY,INT_CLASS)
);
alter table IRL_ACCT_INT comment '分户利息分类明细信息表 undefined';