drop table if exists IRL_ACCR_INFO;
/*==============================================================*/
/* Table: IRL_ACCR_INFO                                           */
/*==============================================================*/
create table IRL_ACCR_INFO
(
    IRL_SEQ_NO varchar(50) not null comment '序号',
    IRL_INTERNAL_KEY varchar(50) not null comment '账户键值',
    ACCR_DATE varchar(8) not null comment '计提日期',
    INT_CLASS varchar(20) not null comment '利息分类',
    ACCT_NO varchar(150) comment '基本存款账号',
    PROD_TYPE varchar(50) not null comment '产品类型',
    BRANCH varchar(20) not null comment '机构',
    SOURCE_TYPE varchar(10) comment '渠道 账户开户时的渠道',
    CCY varchar(3) not null comment '币种',
    CLIENT_NO varchar(20) not null comment '客户号',
    INT_ACCRUED Decimal(17,2) comment '累计计提利息',
    INT_ACCRUED_CTD Decimal(17,2) not null comment '计提日计提金额',
    INT_ACCRUED_DIFF Decimal(15,10) comment '计提金额差额',
    INT_ACCRUED_CALC_CTD Decimal(25,10) comment '计提日计提原金额（实际计算金额）',
    TAX_TYPE varchar(3) comment '税率类型',
    TAX_RATE Decimal(15,8) comment '税率',
    TAX_ACCRUED_CTD Decimal(17,2) comment '计提日利息税',
    TAX_ACCRUED_CALC_CTD Decimal(25,10) comment '计提日利息税原金额（实际计算金额）',
    TAX_ACCRUED_DIFF Decimal(15,10) comment '利息税差额',
    TAX_ACCRUED Decimal(17,2) comment '结息周期内贷方利息税累计金额',
    INT_TYPE varchar(3) comment '利率类型',
    ACTUAL_RATE Decimal(15,8) comment '行内利率',
    FLOAT_RATE Decimal(15,8) comment '浮动利率',
    REAL_RATE Decimal(15,8) comment '执行利率',
    COMPANY varchar(20) comment '法人代码',
    TRAN_SOURCE varchar(6) not null comment '交易发起方',
    ACCOUNTING_STATUS varchar(3) comment '核算状态',
    PROFIT_CENTRE varchar(12) comment '利润中心',
    SOURCE_MODULE varchar(10) comment '源模块',
    BUSINESS_UNIT varchar(10) comment '账套',
    CLIENT_TYPE varchar(3) comment '客户类型',
    IRL_GENE_STR varchar(500) comment '利率因子',
    RULE_ID varchar(500) comment '生效规则号',
    AGG Decimal(38,2) comment '积数',
    INT_AMT Decimal(17,2) comment '利息金额',
    RATE_AMT Decimal(17,2) comment '靠档金额',
    ACCT_SPREAD_RATE Decimal(15,8) comment '分户浮动点数',
    ACCT_PERCENT_RATE Decimal(5,2) comment '分户浮动百分比',
    ACCT_FIXED_RATE Decimal(15,8) comment '分户固定利率',
    MONTH_BASIS varchar(3) comment '月基准天数类型 ',
    YEAR_BASIS varchar(3) comment '年基准',
    REFERENCE varchar(50) comment '交易参考号',
    REMARK varchar(200) comment '备注',
    REVERSAL varchar(1) comment '冲正标识',
    GL_POSTED varchar(1) comment '过账标志',
    NP_PRI varchar(1) comment '本金转非应计标志',
    NP_INT varchar(1) comment '利息转非应计标志',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    primary  key (IRL_SEQ_NO)
);
alter table IRL_ACCR_INFO comment '分户计提流水信息表 undefined';