drop table if exists MB_ACCT_ATTACH;
/*==============================================================*/
/* Table: MB_ACCT_ATTACH                                           */
/*==============================================================*/
create table MB_ACCT_ATTACH
(
    INTERNAL_KEY Decimal(15) not null comment '帐户主键',
    GL_CODE varchar(20) comment '科目代码',
    CONTRA_ACCT_NO varchar(150) comment '对手账号',
    CONTRA_ACCT_NAME varchar(200) comment '对手账号名称',
    ACCT_PROOF_STATUS varchar(2) comment '账户验证状态(二三类账户)',
    ACCT_PROOF_REASON varchar(50) comment '验证失败原因',
    AUTO_DEP varchar(1) comment '是否自动续存',
    FIR_PERIOD varchar(5) comment '首段期数 ',
    MID_PERIOD varchar(5) comment '累进间隔期数 ',
    ADD_AMT Decimal(17,2) comment '累进金额 ',
    ADD_RATIO Decimal(5,2) comment '累进比例',
    CUR_BASIC_DAY varchar(2) comment '当前回收日 ',
    SECOND_REC_DAY varchar(2) comment '第二回收日 ',
    BAL_UPD_TYPE varchar(1) comment '余额更新类型',
    NEXT_STAM_DATE varchar(8) comment '下一账单日',
    LAST_STAM_DATE varchar(8) comment '上一账单日',
    STAGE_CODE varchar(50) comment '期次代码 ',
    OD_FACILITY varchar(1) comment '是否可透支',
    BAL_DIRECT_TYPE varchar(1) comment '余额方向',
    ALLOC_SEQ_TYPE varchar(1) comment '贷款自动还款类型',
    ALLOC_SEQ_PRI varchar(1) comment '贷款本金还款顺序',
    ALLOC_SEQ_INT varchar(1) comment '贷款利息还款顺序',
    ALLOC_SEQ_ODP varchar(1) comment '贷款罚息还款顺序',
    ALLOC_SEQ_ODI varchar(1) comment '贷款复利还款顺序',
    ALLOC_SEQ_FEE varchar(1) comment '贷款费用还款顺序',
    ANNUAL_FLAG varchar(2) comment '是否年检标志',
    ANNUAL_STATUS varchar(2) comment '年检通过状态',
    ACCT_PROPERTY varchar(4),
    FIRST_OVERDUE_DATE varchar(8) comment '最早逾期日期',
    LAST_RESET_DATE varchar(8) comment '上一年检重置日期',
    LAST_STOP_DATE varchar(8) comment '上一年检截止日期',
    AUTO_SETTLE_FLAG varchar(1) comment '自动结清标志  ',
    CYCLE_INT_FLAG varchar(1) comment '按频率付息标志',
    MANUAL_CHANGE_SCHEDULE varchar(1) comment '是否需要手工录入还款计划',
    CONTRIBUTIVE_RATIO Decimal(5,2) comment '出资比例',
    OLD_BASE_ACCT_NO varchar(150) comment '借新还旧旧贷款号',
    OLD_ACCT_SEQ_NO varchar(8) comment '借新还旧旧的发放号',
    HANG_WRITE_OFF_FLAG varchar(1) comment '挂销账标志',
    HANG_TERM varchar(2) comment '挂账期限',
    WRITE_OFF_WAY varchar(2) comment '销账方式',
    SSI_END_DATE varchar(8) comment '贴息截止日期',
    CONTRACTION_DATE varchar(8) comment '变期不变额最后变化日期',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    BAL_CHG_IND varchar(1) comment '余额联动变动标识',
    PAY_OFF_TYPE varchar(200) comment '贷款销户类型',
    PAY_OFF_REASON varchar(200) comment '贷款销户原因',
    FTA_ACCT_FLAG varchar(1) not null comment '是否自贸区账户标识',
    FTA_CODE varchar(10) comment '自贸区代码',
    COMPANY varchar(20) comment '法人代码',
    primary  key (INTERNAL_KEY)
);
alter table MB_ACCT_ATTACH comment '账户辅助信息表 undefined';