drop table if exists MB_DELAY_TRAN_HIST;
/*==============================================================*/
/* Table: MB_DELAY_TRAN_HIST                                           */
/*==============================================================*/
create table MB_DELAY_TRAN_HIST
(
    SEQ_NO varchar(50) not null comment '交易序号',
    SIGN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIMESTAMP varchar(17) comment '到账时间戳',
    INTERNAL_KEY Decimal(15) comment '账户标识符',
    BASE_ACCT_NO varchar(150) comment '账号/卡号',
    ACCT_SEQ_NO varchar(8) comment '账户序列号',
    ACCT_CCY varchar(3) comment '账户币种',
    PROD_TYPE varchar(50) comment '产品类型',
    TRAN_AMT Decimal(17,2) comment '交易金额',
    SOURCE_TYPE varchar(10) comment '渠道类型 ',
    BRANCH varchar(20) comment '交易机构',
    TERMINAL_ID varchar(200) comment '终端标识',
    USER_ID varchar(30) comment '柜员ID',
    NARRATIVE varchar(300) comment '摘要',
    AUTH_USER_ID varchar(30) comment '授权柜员的ID',
    TRAN_DESC varchar(100) comment '交易描述',
    CASH_ITEM varchar(4) comment '现金项目',
    TRAN_NOTE varchar(100) comment '交易附言',
    CLIENT_NO varchar(20) comment '客户号',
    CLIENT_NAME varchar(200) comment '客户名称',
    OTH_INTERNAL_KEY Decimal(15) comment '转账时对方账户标识符',
    OTH_BASE_ACCT_NO varchar(150) comment '对方帐号/卡号',
    OTH_ACCT_SEQ_NO varchar(8) comment '对方账户序列号',
    OTH_PROD_TYPE varchar(50) comment '对方账户产品类型',
    OTH_ACCT_CCY varchar(3) comment '对方账户币种',
    OTH_ACCT_DESC varchar(150) comment '对方账户名称',
    PAY_UNIT varchar(50) comment '交款单位',
    COMMISSION_CLIENT_NAME varchar(200) comment '代办人名称',
    COMMISSION_PHONE varchar(20) comment '代办人电话',
    ARRIVAL_STATUS varchar(1) comment '到账状态',
    TRAN_DATE varchar(8) not null comment '交易日期',
    TRAN_TYPE varchar(10) comment '交易类型',
    TRACK2 varchar(37) comment '卡二磁道',
    TRACK3 varchar(104) comment '卡三磁道',
    TRAN_CCY varchar(3) comment '交易币种',
    DOC_TYPE varchar(10) comment '凭证/票据类型',
    PREFIX varchar(10) comment '前缀',
    VOUCHER_NO varchar(50) comment '凭证号',
    RES_SEQ_NO varchar(50) comment '限制序号',
    EXCHANGE_TRAN_CODE varchar(10) comment '收入方结售汇交易编码',
    EXCHANGE_TRAN_CODET varchar(10) comment '支出方结售汇交易编码',
    OTH_ACCT_NAME varchar(200) comment '对方户名',
    COMPANY varchar(20) comment '法人代码',
    REVOKE_REASON varchar(100) comment '撤销原因',
    REFERENCE varchar(50) comment '交易参考号',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    TIMESTAMP varchar(17) comment '时间戳',
    primary  key (SEQ_NO)
);
alter table MB_DELAY_TRAN_HIST comment '24小时转账流水表 undefined';