drop table if exists MB_DEBT_ASSET_HIST;
/*==============================================================*/
/* Table: MB_DEBT_ASSET_HIST                                           */
/*==============================================================*/
create table MB_DEBT_ASSET_HIST
(
    SEQ_NO varchar(50) not null comment '序号',
    DEBT_ASSET_NO varchar(50) not null comment '抵债资产编号',
    DEBT_ASSET_NAME varchar(200) not null comment '抵债资产名称',
    ACCOUNT_BRANCH varchar(20) not null comment '入账机构',
    CLIENT_NO varchar(20) not null comment '客户号',
    MATERIALS_TYPE varchar(1) not null comment '抵债物资类别 ',
    CERTIFICATE_TYPE varchar(1) not null comment '产权证明种类',
    DEBT_ASSET_AMT Decimal(17,2) comment '代保管抵债资产金额',
    DEBT_ASSET_CCY varchar(3) comment '代保管抵债资产币种',
    DEBT_ASSET_FAIR_VALUE Decimal(17,2) comment '抵债资产公允价值',
    DEBT_ASSET_UNIT varchar(10) comment '抵债资产单位',
    DEBT_ASSET_QUANTITY varchar(15) comment '抵债资产数量',
    NARRATIVE varchar(300) comment '摘要，开户时的账号用途，销户时的销户原因',
    DEBT_ASSET_STATUS varchar(1) comment '抵债资产状态',
    LOAN_NO varchar(150) comment '贷款号',
    RECEIPT_AMT Decimal(17,2) comment '回收金额',
    RECEIPT_CCY varchar(3) comment '还款币种',
    LOAN_IMPAIRMENT_LOSS Decimal(17,2) comment '贷款减值损失',
    NONOPERATING_INCOME Decimal(17,2) comment '营业外收入',
    FEE_TRAN_TYPE varchar(20) comment '收费交易类型',
    FEE_AMT Decimal(17,2) comment '手续费金额',
    RECEIVE_BASE_ACCT_NO varchar(150) comment '收款账号',
    RECEIVE_ACCT_PROD_TYPE varchar(50) comment '收款账户产品类型',
    RECEIVE_ACCT_CCY varchar(3) comment '收款账户币种',
    RECEIVE_ACCT_SEQ_NO varchar(8) comment '收款账户序号',
    ASSETS_DISPOSAL_TYPE varchar(1) comment '抵债资产处置类型',
    ASSETS_DISPOSAL_IND varchar(1) comment '抵债资产是否处置完毕',
    EVENT_TYPE varchar(50) not null comment '事件类型 MB_EVENT_CLASS.EVENT_CLASS',
    ACCOUNTING_STATUS varchar(3) comment '核算状态',
    TRAN_TYPE varchar(10) comment '交易类型',
    TRAN_AMT Decimal(17,2) comment '交易金额',
    AMT_TYPE varchar(10) comment '金额类型',
    REFERENCE varchar(50) comment '交易参考号',
    GL_POSTED varchar(1) not null comment '过账标志 Y:是 N:否',
    TRAN_DATE varchar(8) comment '交易日期',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    REVERSAL varchar(1) comment '冲正标志 Y:是 N:否',
    PROD_TYPE varchar(50) comment '产品类型',
    PROFIT_CENTRE varchar(12) comment '利润中心 FM_PROFIT_CENTRE.PROFIT_CENTRE',
    SOURCE_MODULE varchar(10) comment '模块',
    SOURCE_TYPE varchar(10) comment '渠道 FM_CHANNEL.CHANNEL',
    BANK_SEQ_NO varchar(50) comment '银行交易序号',
    CLIENT_TYPE varchar(3) comment '客户类型',
    COMPANY varchar(20) comment '法人代码',
    primary  key (SEQ_NO)
);
alter table MB_DEBT_ASSET_HIST comment '抵债资产历史流水表 undefined';