drop table if exists MB_IMPOUND_INFO;
/*==============================================================*/
/* Table: MB_IMPOUND_INFO                                           */
/*==============================================================*/
create table MB_IMPOUND_INFO
(
    REFERENCE varchar(50) not null comment '参考号',
    SCHED_NO varchar(30) comment '计划编号',
    INTERNAL_KEY Decimal(15) comment '账户主键',
    BASE_ACCT_NO varchar(150) comment '主账户账号',
    CCY varchar(3) comment '账户币种',
    PROD_TYPE varchar(50) comment '账户类型',
    ACCT_SEQ_NO varchar(8) comment '账户序列号',
    INT_IND varchar(1) comment '是否计息',
    DEPOSIT_TYPE varchar(5) comment '存款类型',
    TRAN_DATE varchar(8) comment '交易日期',
    TRAN_BRANCH varchar(20) comment '交易机构',
    IMPOIND_INT_FLAG varchar(3) comment '标志',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    IMPOUND_AMT Decimal(17,2) comment '扣划金额',
    IMPOUND_INT Decimal(17,2) comment '扣划利息',
    IMPOUND_TAX Decimal(17,2) comment '扣划产生利息税',
    ORIGINAL_INT Decimal(17,2) comment '原计提利息',
    ORIGINAL_INT_ADJ Decimal(17,2) comment '原计提调整利息',
    ACCRUED_INT Decimal(17,2) comment '扣划后金额重新计 提的利息',
    ACCRUED_INT_ADJ Decimal(17,2) comment '扣划后金额重新计 提的调整利息',
    INT_AMT Decimal(17,2) comment '利息金额',
    TOTAL_AMT Decimal(17,2) comment '总金额',
    PLEDGED_TAX_AMT Decimal(17,2) comment '冻结期间利息税',
    PLEDGED_INT_AMT Decimal(17,2) comment '冻结期间产生的利息',
    RESTRAINT_SEQ_NO varchar(50) comment '冻结编号',
    USER_ID varchar(30) comment '交易柜员',
    STATUS varchar(3) comment '状态 S：成功 C：冲正',
    LAW_NO varchar(50) comment '法律文书号',
    NARRATIVE varchar(300) comment '摘要',
    BENEFIT_BASE_ACCT_NO varchar(150) comment '扣划转入账号',
    BENEFIT_PROD_TYPE varchar(50) comment '扣划转入账户类型',
    BENENFIT_CCY varchar(3) comment '扣划转入币种',
    BENENFIT_SEQ_NO varchar(8) comment '扣划转入账号序号',
    BENENFIT_ACCT_NAME varchar(200) comment '扣划转入账户户名',
    DEDUCTION_JUDICIARY_NAME varchar(200) comment '有权机关名称',
    DEDUCTION_TYPE varchar(2) comment '扣划类型',
    TRANSFER_TIMES varchar(5) comment '已扣划次数',
    TRANSFER_AMT Decimal(17,2) comment '已扣划金额',
    JUDICIARY_OFFICER_NAME varchar(200) comment '经办人1姓名',
    JUDICIARY_DOCUMENT_ID varchar(75) comment '经办人1证件号码',
    JUDICIARY_DOCUMENT_TYPE varchar(3) comment '经办人1证件类型',
    JUDICIARY_OTH_OFFICER_NAME varchar(200) comment '经办人2姓名',
    JUDICIARY_OTH_DOCUMENT_ID varchar(75) comment '经办人2证件号码',
    JUDICIARY_OTH_DOCUMENT_TYPE varchar(3) comment '经办人2证件类型',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    INT_INTERNAL_KEY Decimal(15) comment '利息入账账户标识符',
    INT_BASE_ACCT_NO varchar(150) comment '利息转入账号 ',
    INT_PROD_TYPE varchar(50) comment '利息转入账户产品类型',
    INT_ACCT_CCY varchar(3) comment '利息转入账户币种',
    INT_ACCT_SEQ_NO varchar(8) comment '利息转入账户序列号',
    INT_ACCT_NAME varchar(200) comment '利息入账账户户名',
    MOVT_STATUS varchar(1) comment '交易类型   '
);
alter table MB_IMPOUND_INFO comment '扣划记录表 undefined';