drop table if exists MB_LG_REGISTER;
/*==============================================================*/
/* Table: MB_LG_REGISTER                                           */
/*==============================================================*/
create table MB_LG_REGISTER
(
    INTERNAL_KEY Decimal(15) not null comment '帐户主键',
    LG_NO varchar(50) comment '保函编号',
    PROD_TYPE varchar(50) comment '产品类型',
    CONTRACT_NO varchar(50) comment '合同号',
    CMISLOAN_NO varchar(50) comment '借据号',
    OPEN_BRANCH varchar(20) comment '开立机构',
    TRAN_BRANCH varchar(20) comment '交易支行 FM_BRANCH.BRANCH',
    LG_BRANCH varchar(20) comment '担保行',
    COUNTERPARTY_BRANCH varchar(20) comment '反担保行',
    PROFIT_CENTRE varchar(12) comment '利润中心 FM_PROFIT_CENTRE.PROFIT_CENTRE',
    APPLICANT varchar(20) comment '申请人(客户号)',
    BENEFICIARY_ACCT_NO varchar(150) comment '受益人账号',
    BENEFICIARY_NAME varchar(200) comment '受益人名称',
    ACCT_EXEC varchar(30) comment '客户经理',
    CCY varchar(3) comment '币种',
    LG_AMT Decimal(17,2) comment '保函金额',
    RESTRAINT_PER Decimal(15,8) comment '止付比例',
    RESTRAINT_AMT Decimal(17,2) comment '止付金额',
    BACK_ACCT_NO varchar(150) comment '备款入账账号',
    BACK_ACCT_SEQ_NO varchar(8) comment '备款账户序列号',
    BACK_ACCT_CCY varchar(3) comment '备款账号币种',
    BACK_PROD_TYPE varchar(50) comment '备款账号产品类型',
    SETTLE_ACCT_NO varchar(150) comment '结算账号',
    SETTLE_ACCT_SEQ_NO varchar(8) comment '序列号，采用顺序数字，表示在同一账号、账户类型、币种下的不同子账户，比如定期存款序列号',
    SETTLE_ACCT_CCY varchar(3) comment '账户币种，对于AIO账户和一本通账户，账户币种为XXX  FM_CURRENCY.CCY',
    SETTLE_PROD_TYPE varchar(50) comment '结算账户产品类型  MB_PROD_TYPE.PROD_TYPE',
    BOND_ACCT_NO varchar(150) comment '保证金账号',
    BOND_ACCT_SEQ_NO varchar(8) comment '保证金账户序列号',
    BOND_ACCT_CCY varchar(3) comment '保证金账户币种',
    BOND_PROD_TYPE varchar(50) comment '保证金账户产品类型',
    ADVANCED_AMT Decimal(17,2) comment '垫款金额',
    ADVANCED_ACCT_NO varchar(150) comment '垫款贷款账号',
    COMPENSATE_AMT Decimal(17,2) comment '冻结金额',
    PRI_PLTY_ABS Decimal(15,8) comment '垫款固定罚息利率',
    LG_START_DATE varchar(8) comment '保函起始日期',
    LG_END_DATE varchar(8) comment '保函终止日期',
    LG_STATUS varchar(2) comment '保函状态 ',
    LAST_CHANGE_DATE varchar(8) comment '最后变更日期 ',
    USER_ID varchar(30) comment '交易柜员 FM_USER.USER_ID',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    APPR_USER_ID varchar(30) comment '复核柜员',
    TERMINAL_ID varchar(200) comment '终端标识',
    REMARK varchar(200) comment '备注，用来描述制卡原因，比如正常制卡，补换卡等',
    CONTRACT_CCY varchar(3) comment '合同币种',
    ORG_RESTRAINT_AMT Decimal(17,2) comment '保函原始冻结金额',
    BENEFICIARY_DOCUMENT_TYPE varchar(3) comment '证件类型',
    BENEFICIARY_DOCUMENT_ID varchar(75) comment '证件号码',
    NEW_LG_END_DATE varchar(8) comment '终止日期',
    MORTGAGE_CONTRACT_NO varchar(50) comment '抵押合同编号',
    BENEFICIARY_ADDRESS varchar(140) comment '地址',
    COLLAT_VALUE Decimal(17,2) comment '抵押品价值',
    RESTRAINT_SEQ_NO varchar(50) comment '冻结编号',
    LG_COMPENSATE_BALANCE Decimal(17,2) comment '剩余赔付金额',
    COMPENSATE_STATUS varchar(2) comment '保函赔付状态',
    ORIG_LOAN_AMT Decimal(17,2) comment '合同金额',
    TRAN_TIMESTAMP varchar(17) comment '时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    COMPANY varchar(20) comment '法人代码',
    primary  key (INTERNAL_KEY)
);
alter table MB_LG_REGISTER comment '保函信息登记表 undefined';