drop table if exists MB_MISC_HIST;
/*==============================================================*/
/* Table: MB_MISC_HIST                                           */
/*==============================================================*/
create table MB_MISC_HIST
(
    SEQ_NO varchar(50) not null comment '交易序号，系统交易流水号',
    TRAN_DATE varchar(8) not null comment '交易日期',
    TERMINAL_ID varchar(200) comment '终端，表示交易发起的终端号',
    BRANCH varchar(20) comment '分行，分行代号',
    TRAN_TYPE varchar(10) comment '交易类型',
    CR_DR_MAINT_IND varchar(1) comment '借贷标记，当前交易是借方交易还是贷方交易',
    TRAN_AMT Decimal(17,2) comment '交易金额，当前交易的交易金额',
    CCY varchar(3) comment '币种，交易币种',
    REFERENCE varchar(50) comment '参考号',
    CHANNEL_SEQ_NO varchar(50) comment '渠道流水号',
    EFFECT_DATE varchar(8) comment '生效日期，交易的生效日期',
    SOURCE_MODULE varchar(10) comment '来源模块，建立帐户限制的模块  例如DP代表国内支付，RB代表存款模块',
    SOURCE_TYPE varchar(10) comment '来源类型，交易的发起渠道',
    PROFIT_CENTRE varchar(12) comment '利润中心，会计分录六要素之一，类似于清算部门概念',
    TRAN_HIST_SEQ_NO varchar(50) comment '交易流水号',
    TRAN_DESC varchar(100) comment '交易描述',
    NARRATIVE varchar(300) comment '摘要',
    CLIENT_NO varchar(20) comment '客户号，该帐户的开立人',
    CLIENT_NAME varchar(200) comment '客户名称，系统客户名称',
    DOCUMENT_TYPE varchar(3) comment '证件类型，帐户开立的证件类型',
    DOCUMENT_ID varchar(75) comment '证件号，帐户开立的证件号码',
    RATE_TYPE varchar(3) comment '利率类型',
    CONTRA_CCY varchar(3) comment '对方币种',
    CONTRA_EQUIV_AMT Decimal(17,2) comment '对方等值金额',
    BASE_EQUIV_AMT Decimal(17,2) comment '通过汇率换算后的金额',
    CROSS_RATE Decimal(15,8) comment '交叉汇率',
    REVERSAL_TRAN_TYPE varchar(10) comment '冲正交易类型，如果该交易是冲正交易，该栏位必须填写否则不填。例如：现金存入冲正-D011',
    REVERSAL_TRAN_DATE varchar(8) comment '冲正交易日期',
    TRACE_ID varchar(50) comment '原交易序号',
    USER_ID varchar(30) comment '交易柜员号',
    AUTH_USER_ID varchar(30) comment '授权柜员的ID',
    PRIMARY_TRAN_SEQ_NO varchar(50) comment '主交易序号',
    BR_SEQ_NO varchar(50) comment '前端流水号',
    FLOAT_DAYS varchar(5) comment '浮动天数',
    POST_DATE varchar(8) comment '入帐日期',
    TFR_BRANCH varchar(20) comment '对方交易机构',
    CONV_BASE varchar(1),
    MAIN_SEQ_NO varchar(50) comment '主流水号',
    COUNTRY varchar(3) comment '国家',
    COSTUMER_ID varchar(15),
    COUNTER_PAY_FLAG varchar(1) comment '柜面收付标志',
    D2_REFERENCE varchar(50) comment '参考号',
    DEPT_CODE varchar(3) comment '现金支出项目编码',
    BUSINESS_UNIT varchar(10) comment '帐套',
    BANK_SEQ_NO varchar(50) comment '银行交易序号',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    DOC_TYPE varchar(10) comment '凭证/票据类型',
    PREFIX varchar(10) comment '票据前缀',
    VOUCHER_NO varchar(50) comment '交易参考号',
    TRAN_STATUS varchar(3) comment '交易状态',
    REVERSAL varchar(1) comment '冲正标志',
    SERV_CHARGE varchar(1) comment '服务费标识 ',
    PROGRAM_ID varchar(20) comment '交易码',
    COMPANY varchar(20) comment '法人代码',
    GL_POSTED varchar(1) comment '过账标志',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    PRIMARY_EVENT_TYPE varchar(50) default NULL   comment '主交易事件',
    PRINT_CNT varchar(5) comment '打印次数',
    primary  key (SEQ_NO,TRAN_DATE)
);
alter table MB_MISC_HIST comment '现金交易流水表 undefined';