drop table if exists MB_RESTRAINTS;
/*==============================================================*/
/* Table: MB_RESTRAINTS                                           */
/*==============================================================*/
create table MB_RESTRAINTS
(
    INTERNAL_KEY Decimal(15) not null comment '帐户主键',
    RESTRAINT_TYPE varchar(3) not null comment '限制类型 ',
    RES_SEQ_NO varchar(50) not null comment '限制序号',
    START_CHEQUE_NO varchar(13) comment '起始支票号码',
    END_CHEQUE_NO varchar(13) comment '终止支票号码',
    START_DATE varchar(8) comment '生效日期',
    END_DATE varchar(8) comment '终止日期',
    START_AMT Decimal(17,2) comment '起始金额',
    END_AMT Decimal(17,2) comment '截止金额',
    PLEDGED_AMT Decimal(17,2) comment '限制金额',
    PLEDGED_ACCT_TYPE varchar(3) comment '抵押账户类型',
    PLEDGED_ACCT_NO varchar(150) comment '抵押账号',
    RES_ACCT_RANGE varchar(1) comment '限制账户范围   ',
    LAST_CHANGE_DATE varchar(8) comment '最后变更日期 ',
    LAST_CHANGE_USER_ID varchar(30) comment '上次修改柜员',
    NARRATIVE varchar(300) comment '摘要，开户时的账号用途，销户时的销户原因',
    STATUS varchar(3) comment '状态',
    STL_SEQ_NO varchar(50) comment '结算流水号',
    SOURCE_MODULE varchar(10) comment '模块',
    CHANNEL_SEQ_NO varchar(50) comment '渠道流水号',
    TRAN_TYPE varchar(10) comment '交易类型',
    RES_PRIORITY varchar(5) comment '冻结级别(限制级别)',
    OTH_BANK_CODE varchar(20) comment '其他行代码',
    OTH_ACCT_NO varchar(150) comment '其他账号',
    OTH_ACCT_DESC varchar(150) comment '对方账户名称',
    PURPOSE_CODE varchar(10) comment '目的代码',
    SPEC_CODE varchar(10) comment '指定他行信息',
    REFERENCE varchar(50) comment '交易参考号',
    MSG_CLIENT varchar(250) comment '客户信息',
    MSG_BANK varchar(150) comment '银行信息',
    NO_OF_PAYMENT varchar(5) comment '总支付笔数',
    PAYMENT_MADE varchar(5) comment '已支付笔数',
    TO_PAY_AMT Decimal(17,2) comment '支付金额',
    PAID_AMT Decimal(17,2) comment '已还金额',
    TRAN_AMT Decimal(17,2) comment '交易金额',
    FULL_FREEZE_IND varchar(1) comment '全额冻结标志',
    APPROVAL_DATE varchar(8) comment '复核日期',
    INTERRUPT varchar(1) comment '是否中断',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    PREFIX varchar(10) comment '前缀',
    APPROVAL_STATUS varchar(1) comment '复核标志',
    APPR_USER_ID varchar(30) comment '复核柜员',
    USER_ID varchar(30) comment '交易柜员',
    PROGRAM_ID varchar(20) comment '交易码',
    TERM varchar(5) comment '存期',
    TERM_TYPE varchar(1) comment '存期类型',
    OTH_PROD_TYPE varchar(50) comment '第三方产品类型  ',
    PLEDGED_ACCT_CCY varchar(3) comment '抵押账户币种',
    OTH_ACCT_CCY varchar(3) comment '对方账户币种 ',
    PLEDGED_BASE_ACCT_NO varchar(150) comment '抵押主账号',
    OTH_BASE_ACCT_NO varchar(150) comment '对方帐号/卡号',
    DOC_TYPE varchar(10) comment '凭证类型',
    RESTRAINT_JUDICIARY_NAME varchar(200) comment '冻结机关名称',
    RESTRAINT_LAW_NO varchar(50) comment '冻结机关法律文书号',
    RELEASE_JUDICIARY_NAME varchar(200) comment '解冻机关名称',
    RELEASE_LAW_NO varchar(50) comment '解冻机关法律文书号',
    DEDUCTION_JUDICIARY_NAME varchar(200) comment '有权机关名称',
    DEDUCTION_LAW_NO varchar(50) comment '扣划法律文书号',
    JUDICIARY_OFFICER_NAME varchar(200) comment '经办人1姓名',
    JUDICIARY_DOCUMENT_TYPE varchar(3) comment '经办人1证件类型  ',
    JUDICIARY_DOCUMENT_ID varchar(75) comment '经办人1证件号码',
    JUDICIARY_OTH_OFFICER_NAME varchar(200) comment '经办人2姓名',
    JUDICIARY_OTH_DOCUMENT_TYPE varchar(3) comment '经办人2证件类型 ',
    JUDICIARY_OTH_DOCUMENT_ID varchar(75) comment '经办人2证件号码',
    BRANCH varchar(20) comment '机构代码',
    COMPANY varchar(20) comment '法人代码',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    SUB_RESTRAINT_CLASS varchar(2) comment '子限制类别',
    primary  key (INTERNAL_KEY,RESTRAINT_TYPE,RES_SEQ_NO)
);
alter table MB_RESTRAINTS comment '帐户限制表 undefined';