drop table if exists MB_TRAN_HIST;
/*==============================================================*/
/* Table: MB_TRAN_HIST                                           */
/*==============================================================*/
create table MB_TRAN_HIST
(
    SEQ_NO varchar(50) not null comment '序号',
    INTERNAL_KEY Decimal(15) comment '帐户主键',
    TRAN_DATE varchar(8) not null comment '交易日期',
    TRAN_TYPE varchar(10) comment '交易类型',
    EVENT_TYPE varchar(50) comment '事件类型 MB_EVENT_CLASS.EVENT_CLASS',
    CCY varchar(3) comment '币种',
    CR_DR_MAINT_IND varchar(1) comment '借贷标志  C:贷 D：借',
    TRAN_AMT Decimal(17,2) comment '交易金额',
    BRANCH varchar(20) comment '机构代码',
    SOURCE_TYPE varchar(10) comment '渠道 FM_CHANNEL.CHANNEL',
    TERMINAL_ID varchar(200) comment '终端标识',
    USER_ID varchar(30) comment '交易柜员 FM_USER.USER_ID',
    REFERENCE varchar(50) comment '交易参考号',
    TRAN_CATEGORY varchar(1) comment '交易种类',
    BANK_SEQ_NO varchar(50) comment '银行交易序号',
    EFFECT_DATE varchar(8) comment '生效日期',
    ACCT_TRAN_FLAG varchar(1) comment '账户交易标志',
    REVERSAL_TRAN_TYPE varchar(10) comment '冲正交易类型  MB_TRAN_DEF.TRAN_TYPE',
    REVERSAL_DATE varchar(8) comment '冲正日期',
    PREVIOUS_BAL_AMT Decimal(17,2) comment '交易前余额',
    ACTUAL_BAL_AMT Decimal(17,2) comment '实际余额',
    BASE_ACCT_NO varchar(150) comment '账号',
    ACCT_SEQ_NO varchar(8) comment '账户序列号',
    ACCT_CCY varchar(3) comment '账户币种，',
    PROD_TYPE varchar(50) comment '产品类型',
    ACCT_BRANCH varchar(20) comment '账户开户行',
    GL_CODE varchar(20) comment '科目代码 AC_SUBJECT.SUBJECT_CODE',
    ACCT_DESC varchar(150) comment '账户描述',
    TRACE_ID varchar(50) comment '跟踪ID',
    NARRATIVE varchar(300) comment '摘要，开户时的账号用途，销户时的销户原因',
    AUTH_USER_ID varchar(30) comment '授权柜员',
    APPR_USER_ID varchar(30) comment '复核柜员',
    TRAN_DESC varchar(100) comment '交易描述',
    TRAN_TIMESTAMP varchar(17) comment '交易时间戳',
    CASH_ITEM varchar(4) comment '现金项目',
    TRAN_NOTE varchar(100) comment '交易附言',
    TRAN_STATUS varchar(3) comment '状态',
    ACCT_REAL_FLAG varchar(1) comment '账户虚实标志  ',
    CLIENT_NO varchar(20) comment '客户号',
    CLIENT_NAME varchar(200) comment '客户名称',
    PROFIT_CENTRE varchar(12) comment '利润中心 FM_PROFIT_CENTRE.PROFIT_CENTRE',
    BUSINESS_UNIT varchar(10) comment '帐套',
    SOURCE_MODULE varchar(10) comment '模块',
    RECEIPT_NO varchar(30) comment '回收号',
    PRIMARY_TRAN_SEQ_NO varchar(50) comment '主交易序号',
    RATE_TYPE varchar(3) comment '利率类型 IRL_INT_TYPE.INT_TAX_TYPE',
    OTH_SEQ_NO varchar(50) comment '对方交易流水号，比如转账时，转出交易对应的此字段为转入交易流水号，转入交易对应的此字段为转出交易流水号',
    OTH_INTERNAL_KEY Decimal(15) comment '转账时对方账户标识符',
    OTH_BRANCH varchar(20) comment '对方账户开户机构',
    OTH_BANK_NAME varchar(200) comment '对方银行名称',
    OTH_BANK_CODE varchar(20) comment '其他行代码',
    OTH_BASE_ACCT_NO varchar(150) comment '对方帐号/卡号',
    OTH_ACCT_SEQ_NO varchar(8) comment '对方账户序列号',
    OTH_PROD_TYPE varchar(50) comment '第三方产品类型  MB_PROD_TYPE.PROD_TYPE',
    OTH_ACCT_CCY varchar(3) comment '对方账户币种  FM_CURRENCY.CCY',
    OTH_ACCT_DESC varchar(150) comment '对方账户名称',
    OTH_REFERENCE varchar(50) comment '对方交易参考号',
    SERV_CHARGE varchar(1) comment '服务费标识 Y:是 N:否',
    SORT_PRIORITY varchar(5) comment '优先级',
    FH_SEQ_NO varchar(50) comment '资金冻结流水号',
    DOC_TYPE varchar(10) comment '凭证类型 TB_VOUCHER_DEF.DOC_TYPE',
    PREFIX varchar(10) comment '前缀',
    VOUCHER_NO varchar(50) comment '凭证号',
    BAL_TYPE varchar(2) comment '余额类型',
    PRINT_CNT varchar(5) comment '打印次数',
    CONTRA_CCY varchar(3) comment '对方币种',
    CONTRA_EQUIV_AMT Decimal(17,2) comment '对方等值金额',
    BASE_EQUIV_AMT Decimal(17,2) comment '通过汇率换算后本币金额 ',
    DOCUMENT_TYPE varchar(3) comment '证件类型 CIF_DOCUMENT_TYPE.DOCUMENT_TYPE',
    DOCUMENT_ID varchar(75) comment '证件号码',
    CROSS_RATE Decimal(15,8) comment '交叉汇率',
    CHANNEL_SEQ_NO varchar(50) comment '渠道流水号',
    SETTLEMENT_DATE varchar(8) comment '清算日期',
    CONTRAST_BAT_NO varchar(50) comment '批次号',
    BIZ_TYPE varchar(4) comment '中间业务类型',
    RATE_FLAG varchar(1) comment '利率标志 ',
    FROM_CCY varchar(3) comment '转移币种   FM_CURRENCY.CCY',
    FROM_AMOUNT Decimal(17,2) comment '转移金额 ',
    FROM_RATE_FLAG varchar(1) comment '交易汇率标志',
    FROM_XRATE Decimal(15,8) comment '汇率值 ',
    FROM_ID varchar(1) comment '牌价类型 ',
    TO_CCY varchar(3) comment '转移币种  FM_CURRENCY.CCY',
    TO_AMOUNT Decimal(17,2) comment '转移金额',
    TO_RATE_FLAG varchar(1) comment '交易汇率标志 ',
    TO_XRATE Decimal(15,8) comment '汇率值',
    TO_ID varchar(1) comment '牌价类型 ',
    OV_CROSS_RATE Decimal(15,8) comment '实际交易时修改交叉汇率',
    OV_TO_AMOUNT Decimal(17,2) comment '根据实际交易时修改交叉汇率计算的金额',
    PBK_UPD_FLAG varchar(1) default 'N' comment '是否补登存',
    COMPANY varchar(20) comment '法人代码',
    LENDER varchar(20) comment '贷款人',
    CLIENT_TYPE varchar(3) comment '客户类型',
    AMT_TYPE varchar(10) comment '金额类型',
    ACCT_STATUS varchar(3) comment '核算状态',
    ACCOUNTING_STATUS varchar(3) comment '核算状态',
    WITHDRAWAL_TYPE varchar(1) comment '支取方式 ',
    REVERSAL varchar(1) comment '冲正标志 Y:是 N:否',
    PAY_UNIT varchar(50) comment '交款单位',
    COMMISSION_CLIENT_NAME varchar(200) comment '代办人客户名称',
    COMMISSION_PHONE varchar(20) comment '代办人电话',
    PROGRAM_ID varchar(20) comment '交易码',
    PRIMARY_EVENT_TYPE varchar(50) comment '主事件类型',
    AMT_CALC_TYPE varchar(10) comment '金额计算类型',
    GL_POSTED varchar(1) comment '过账标志 Y:是 N:否',
    TRAN_TIME Decimal(11,0) comment '交易时间',
    ROUTER_KEY varchar(100) comment '分库路由关键字',
    TRAN_METHOD varchar(2) comment '转账方式 01:实时到账 02:次日到账',
    CHANNEL_TYPE varchar(20) comment '渠道类型',
    REVERSAL_SEQ_NO varchar(50) comment '冲正流水号',
    LIMIT_REF varchar(200) comment '限额编码',
    primary  key (SEQ_NO)
);
alter table MB_TRAN_HIST comment '金融交易流水表 undefined';

drop index MB_TRAN_HIST_IND1 on MB_TRAN_HIST;
/*==============================================================*/
/* Index: MB_TRAN_HIST_IND1                                           */
/*==============================================================*/
create index MB_TRAN_HIST_IND1 on MB_TRAN_HIST (
    INTERNAL_KEY
);

drop index MB_TRAN_HIST_IND2 on MB_TRAN_HIST;
/*==============================================================*/
/* Index: MB_TRAN_HIST_IND2                                           */
/*==============================================================*/
create index MB_TRAN_HIST_IND2 on MB_TRAN_HIST (
    REFERENCE
);