TRUNCATE TABLE rc_list_org;
INSERT INTO rc_list_org (LIST_ORG, LIST_ORG_NAME, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('000000', '本行', NULL, NULL);
INSERT INTO rc_list_org (LIST_ORG, LIST_ORG_NAME, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('100000', '联合国、OFAC等国际组织', NULL, NULL);
INSERT INTO rc_list_org (LIST_ORG, LIST_ORG_NAME, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('200501', '公安', NULL, NULL);
INSERT INTO rc_list_org (LIST_ORG, LIST_ORG_NAME, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('300501', '工商总局', NULL, NULL);
INSERT INTO rc_list_org (LIST_ORG, LIST_ORG_NAME, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('400501', '高法', NULL, NULL);
INSERT INTO rc_list_org (LIST_ORG, LIST_ORG_NAME, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('500501', '工信部', NULL, NULL);
INSERT INTO rc_list_org (LIST_ORG, LIST_ORG_NAME, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('600501', '中国支付清算协会', NULL, NULL);
INSERT INTO rc_list_org (LIST_ORG, LIST_ORG_NAME, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('700501', '银行卡清算', NULL, NULL);

COMMIT;
