TRUNCATE TABLE rc_list_category;
INSERT INTO rc_list_category (LIST_CATEGORY, LIST_CATEGORY_DESC, APP_IND, PROPERTY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('01', '人行黑名单', 'E', '1', NULL, NULL);
INSERT INTO rc_list_category (LIST_CATEGORY, LIST_CATEGORY_DESC, APP_IND, PROPERTY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('02', '人行灰名单', 'E', '1', NULL, NULL);
INSERT INTO rc_list_category (LIST_CATEGORY, LIST_CATEGORY_DESC, APP_IND, PROPERTY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('10', '人行261名单(六个月无交易)', 'I', '1', NULL, NULL);
INSERT INTO rc_list_category (LIST_CATEGORY, LIST_CATEGORY_DESC, APP_IND, PROPERTY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('11', '行内黑名单', 'I', '1', NULL, NULL);
INSERT INTO rc_list_category (LIST_CATEGORY, LIST_CATEGORY_DESC, APP_IND, PROPERTY, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('12', '行内白名单', 'I', '2', NULL, NULL);

COMMIT;
