TRUNCATE TABLE irl_taxrate_info;
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('CAN', 'ALL', '20171025', '10', 'DKJ');
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('CHN', '50', '20171025', '20', 'LXS');
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('CHN', '50', '20190501', '10', 'LXS');
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('CHN', '51', '20171025', '20', 'LXS');
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('CHN', '51', '20190501', '10', 'LXS');
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('CHN', '61', '20171025', '20', 'LXS');
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('CHN', '61', '20190501', '10', 'LXS');
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('MYS', 'ALL', '20171025', '10', 'DKJ');
INSERT INTO irl_taxrate_info (COUNTRY, PROVINCE, EFFECT_DATE, TAX_RATE, TAXRATE_CODE) VALUES ('USA', 'ALL', '20171025', '10', 'DKJ');

COMMIT;
