TRUNCATE TABLE irl_system;
INSERT INTO irl_system (COY_NAME, COY_SHORT, RUN_DATE, MTH_END_DATE, YR_END_DATE, BASE_CCY, LOCAL_CCY, DEFAULT_BRANCH, LAST_RUN_DATE, NEXT_RUN_DATE, QUR_END_DATE, HALF_END_DATE, SYSTEM_PHASE, DEFAULT_RATE_TYPE, QUOTE_BALANCE_TYPE, INT_EVENT_VALUE, COMPANY, GL_MERGE_TYPE, DEFAULT_CHARGE_RATE_TYPE, TRAN_TIMESTAMP, TRAN_TIME) VALUES ('神州银行股份有限公司', '神州银行', '20180629', NULL, NULL, 'CNY', 'CNY', '9999', '20180628', '20180630', NULL, NULL, NULL, 'CTR', 'CA', 'ACR', NULL, 'N', 'ZSL', '20180227091443', '1519694083');

COMMIT;
